### PR TITLE
dedup get execution weights

### PR DESCRIPTION
**Pull request by pattyshack**

### CODE REVIEW

**Review by SaveTheRbtz — APPROVED** [review]
You would also need to bump minimum go version everywhere to 1.18

**Review by SaveTheRbtz — APPROVED** [review]

**Comment by pattyshack** [comment]
it's already at 1.18? https://github.com/onflow/flow-go/blob/master/go.mod#L3

**Review by janezpodhostnik — APPROVED** [review]
Nice. Yeah looks like we are good to go to use generics.

**Comment by pattyshack** [comment]
bors merge

**Pull request merged**
