### PR TITLE
[EVM] Remove an old comment

### PR DESCRIPTION
**Pull request by sideninja**
Just an update to the wrong comment.

### CODE REVIEW

**Review by peterargue — APPROVED** [review]

**Review by peterargue — APPROVED** [review]

**Review by janezpodhostnik — APPROVED** [review]

**Review by ramtinms — APPROVED** [review]

**Review by turbolent — APPROVED** [review]
As noted in the FLIP and the Notion doc, we should clarify the behaviour.

What happens when the EVM transaction fails?

**Comment by sideninja** [comment]
> As noted in the FLIP and the Notion doc, we should clarify the behaviour.
> 
> What happens when the EVM transaction fails?

Right now Cadence transaction fails as well and the state reverts. As per suggestion, there will be another set of methods with `try` prefix or whatever the implementation detail, basically gracefully handling failure. No matter the future changes to this, the fact is the current comment based on the current implementation is wrong so better to remove it.

**Comment by sideninja** [comment]
p.s. I don't know why I struggle to merge this, the CI is just going nuts on this one.

**Comment by turbolent** [comment]
> Right now Cadence transaction fails as well and the state reverts. 

Sounds good, let's document that in the comment for the function please. Currently the documentation of the behaviour is just removed, which leaves that question open

**Comment by turbolent** [comment]
CI changed on master, so master needed to get merged into this

**Comment by turbolent** [comment]
@sideninja Can you please re-add a description like noted above before merging, or at least in a follow-up PR?

**Pull request closed without merging**
