### PR TITLE
Add missing System Contracts

### PR DESCRIPTION
**Pull request by jribbink**
Closes https://github.com/onflow/flow-go/issues/6210
Closes https://github.com/onflow/flow-go/issues/6142

### CODE REVIEW

**Comment by turbolent** [comment]
@joshuahannan Does this look right?

**Review by turbolent — APPROVED** [review]
Thanks!

**Comment by turbolent** [comment]
For context: this is for https://github.com/onflow/flow-cli/issues/1669

**Comment by joshuahannan** [comment]
Looks good, but can you also add `FungibleTokenMetadataViews` and `FungibleTokenSwitchboard`? They aren't in there yet either. Thank you!

**Review by turbolent — APPROVED** [review]
👍

**Review by janezpodhostnik — APPROVED** [review]
lgtm. Thank you!

**Review by joshuahannan — APPROVED** [review]

**Pull request merged**
