### PR TITLE
[Flow EVM] Implement the `EVMAddress.storageAt()` method

### PR DESCRIPTION
**Pull request by m-Peter**
Closes: https://github.com/onflow/flow-go/issues/6178

### CODE REVIEW

**Comment by ramtinms** [comment]
Hmm, lets wait on this, I don't think the implementation should be here and allow access to the raw memory within Cadence. Storage_At is usually an offchain logic

**Comment by m-Peter** [comment]
> Hmm, lets wait on this, I don't think the implementation should be here and allow access to the raw memory within Cadence. Storage_At is usually an offchain logic

@ramtinms How so? :thinking: This isn't any different than `EVMAddress.code()`, for example.
Is it possible to somehow access the `StateDB` from the EVM Gateway?

For context:
- [eth_getStorageAt](https://docs.infura.io/api/networks/ethereum/json-rpc-methods/eth_getstorageat) JSON-RPC API spec
- https://github.com/onflow/go-ethereum/blob/fb8de1862fe8db58b76aebf13f8f1183e6c67608/internal/ethapi/api.go#L886-L900 Geth implementation

**Comment by ramtinms** [comment]
The stateDB accepts Ledger interface and can be used to directly use the archive node interface.

**Comment by bluesign** [comment]
I think it is good to have `EVMAddress.storageAt()` at Cadence, but I also understand the concerns here. Eventually this will cause big load on ANs.

**Comment by ramtinms** [comment]
Another reason I'm concerned about exposing this is, that slot storage is heavily EVM compiler-dependent, it's very hard to have a meaningful understanding of hash values returned from the storage and might result in user errors.

**Review by ramtinms — APPROVED** [review]
Looks good to me, but lets not merge it yet.

**Review by janezpodhostnik — APPROVED** [review]

**Comment by m-Peter** [comment]
Closing this as it was completed by alternative approach in https://github.com/onflow/flow-evm-gateway/pull/363

**Pull request closed without merging**
