### PR TITLE
Skip persisting execution state delta

### PR DESCRIPTION
**Pull request by zhangchiqing**

### CODE REVIEW

**Review by jordanschalm — APPROVED** [review]
LGTM

**Comment by Kay-Zee** [comment]
This would probably be a decent speed boost. We're certain that we don't need to persist this? All the data here is repeated in the WAL? or are there things only stored here?

**Comment by psiemens** [comment]
Do we risk anything by skipping the saving of deltas? I'm not really sure what the tradeoff is here.

**Comment by Kay-Zee** [comment]
The upside is saving DB writes. But I too am a little worried about what we don't save. A little FOMO i guess. The current assumption is that we don't really use these state interactions much anymore, since we save similar data in the WAL. We had it here previously for state sync, which is currently turned off.

**Review by psiemens — APPROVED** [review]
If the deltas are only used for state syncing, which we've disabled and don't need, then I think we can safely merge this. 👍

**Comment by zhangchiqing** [comment]
The state interactions are only used by state sync. We had ideas to move it to a different storage, since it doesn't need to be in badger. But since state sync is disabled, we could just remove it for now.

**Pull request merged**
