### PR TITLE
Move StorageSnapshot from execution/state/delta to fvm/state

### PR DESCRIPTION
**Pull request by pattyshack**
Note that I'm slowly folding execution/state/delta's logic into fvm/state. View will be decomposed into SpockView and StorageView (we'll move away from the Delta structure).

### CODE REVIEW

**Review by SaveTheRbtz — APPROVED** [review]

**Review by koko1123 — APPROVED** [review]
Looks good to me!

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors retry

**Comment by pattyshack** [comment]
bors merge

**Pull request merged**
