### PR TITLE
Port of complete removal of extralogs

### PR DESCRIPTION
**Pull request by m4ksio**
#2664 to master

### CODE REVIEW

**Review by ramtinms — APPROVED** [review]
Looks good to me, goodbye extralogs

**Comment by Kay-Zee** [comment]
Could we resolve the conflicts and fix the lint issues please? For the deadcode/unused code, let's just remove

**Review by janezpodhostnik — APPROVED** [review]

**Comment by zhangchiqing** [comment]
can we merge this PR?

**Comment by bluesign** [comment]
I depend on this this PR, any chance we can merge this?

**Pull request merged**
