### PR TITLE
Move environment specific meter constants from meter/ to environment/

### PR DESCRIPTION
**Pull request by pattyshack**

### CODE REVIEW

**Review by Tonix517 — APPROVED** [review]

**Review by SaveTheRbtz — APPROVED** [review]

**Comment by pattyshack** [comment]
bors merge

**Review by janezpodhostnik — APPROVED** [review]

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors retry

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors retry

**Comment by pattyshack** [comment]
The test setup is done in such a way that we can't make changes that breaks the emulator.  The circular dependency is pretty messed up, especially since the emulator is version pinned ...

**Comment by pattyshack** [comment]
sigh ... for now, i've duplicated the constants instead

**Comment by pattyshack** [comment]
bors merge

**Pull request merged**
