### PR TITLE
Auto Cadence Update: Add container static types

### PR DESCRIPTION
**Pull request by turbolent**
Auto generated PR to update Cadence version.

References: https://github.com/onflow/cadence/pull/1125

### CODE REVIEW

**Comment by janezpodhostnik** [comment]
@SupunS @turbolent There are some tests breaking with the introduction of this change.

One of them is also the test that checks if the state commitment after setting up a new chain with all the core contracts has changed. It did change. Does this mean that a state migration will be needed here?

**Comment by turbolent** [comment]
@janezpodhostnik That is to be expected: the related Cadence PR changed the storage format, it added  static type information to all stored arrays and dictionaries. 

This results in a different state commitment for the genesis block. To fix the tests, replace the expected state commitment hash with the the new one, and re-run the tests. If the hash keeps on changing, there is a determinism problem and we need to investigate.

**Comment by janezpodhostnik** [comment]
got it, thank you @turbolent. Any idea on how do we make sure this doesn't get deployed anywhere without the matching migration? Do we wait with merging?

**Comment by janezpodhostnik** [comment]
I'm not sure how to fix the integration tests here.
I think this is the root cause of the issue:

```
··· DOCK: (clogs ) execution_2               (86cfcb90fb3449499a07a75a1da8b36f49aa875ded99f8c9ec5cc491263c32c2) - o{"level":"info","node_role":"execution","node_id":"b73378345d73a7cd8c6ec8e4be2c42322c645d04da6871ee216b544cb43e5ac3","engine":"computation","component":"block_computer","txHash":"33f84536f30f37c3df1f5ce9b5fbd7ec526b43852e3218790ca61f14b0769be1","blockHeight":3,"ledgerInteractionUsed":494947,"time":"2021-09-02T20:07:53Z","message":"transaction executed with error"}
··· DOCK: (clogs ) execution_2               (86cfcb90fb3449499a07a75a1da8b36f49aa875ded99f8c9ec5cc491263c32c2) - {"level":"debug","node_role":"execution","node_id":"b73378345d73a7cd8c6ec8e4be2c42322c645d04da6871ee216b544cb43e5ac3","engine":"computation","component":"block_computer","tx_id":"33f84536f30f37c3df1f5ce9b5fbd7ec526b43852e3218790ca61f14b0769be1","error_message":"[Error Code: 1101] cadence runtime error Execution failed:\nerror: invalid container update: expected a subtype of 'Never'\n   --> f8d6e0586b0a20c7.FlowEpoch:685:47\n","error_code":1101,"time":"2021-09-02T20:07:53Z","message":"transaction execution failed"}
··· DOCK: (clogs ) execution_2               (86cfcb90fb3449499a07a75a1da8b36f49aa875ded99f8c9ec5cc491263c32c2) - U{"level":"info","node_role":"execution","node_id":"b73378345d73a7cd8c6ec8e4be2c42322c645d04da6871ee216b544cb43e5ac3","engine":"computation","component":"block_computer","txHash":"33f84536f30f37c3df1f5ce9b5fbd7ec526b43852e3218790ca61f14b0769be1","traceID":"","timeSpentInMS":21,"time":"2021-09-02T20:07:53Z","message":"transaction executed"}
··· DOCK: (clogs ) execution_2               (86cfcb90fb3449499a07a75a1da8b36f49aa875ded99f8c9ec5cc491263c32c2) - 5{"level":"error","node_role":"execution","node_id":"b73378345d73a7cd8c6ec8e4be2c42322c645d04da6871ee216b544cb43e5ac3","engine":"computation","component":"block_computer","error_message":"[Error Code: 1101] cadence runtime error Execution failed:\nerror: invalid container update: expected a subtype of 'Never'\n   --> f8d6e0586b0a20c7.FlowEpoch:685:47\n","block_id":"e8d8e9128b24cabf00716cbeec7f26db54f94468a1eff2b82baf13636eddbb10","system_chunk_error":true,"critical_error":true,"time":"2021-09-02T20:07:53Z","message":"error executing system chunk transaction"}
```

But that line of the contract is just [this](https://github.com/onflow/flow-core-contracts/blob/6e64b6aeb52780cf5d5082bea5aeb5fbfa179eec/contracts/epochs/FlowEpoch.cdc#L685), so I cant imagine why we get this error... 

Any ideas @SupunS

**Comment by SupunS** [comment]
Oh that looks like a cadence bug. Good catch!

This reproduces it:
```
let names: [{String: UInt64}] = []
names.append({})    // <-- this empty dictionary don't have a type!
names[0]["foo"] = 4
```

I think the issue is with type inferring for the empty dictionary in func-args. 

This PR: https://github.com/onflow/cadence/pull/1033 fixes this. Probably we should get that merged as well for the release.

**Comment by SupunS** [comment]
The fix is merged to Cadence now. All checks seems to be passing: https://github.com/onflow/flow-go/pull/1261

**Pull request merged**
