### PR TITLE
Consensus Voting V2

### PR DESCRIPTION
**Pull request by zhangchiqing**
Merge Consensus Voting V2 into master

### CODE REVIEW

**Comment by zhangchiqing** [comment]
```
        container.go:219: container start failure: Error response from daemon: driver failed programming external connectivity on endpoint access_1 (197e48c2618ed01ffccc7c1f0e6fc97eed3da184a5f422cb47f0e408c1f11012): Bind for 0.0.0.0:41541 failed: port is already allocated
        access_api_test.go:82: 
            	Error Trace:	access_api_test.go:82
            	Error:      	Received unexpected error:
            	            	dial tcp :44135: connect: connection refused
            	Test:       	TestAccessSuite/TestHTTPProxyPortOpen
            	Messages:   	http proxy port not open on the access node
```

Hit this a few times, seems the docker contains were not removed completed in the previous tests running, causing the next test case unable to start the container

**Comment by zhangchiqing** [comment]
```
--- FAIL: TestRandomizedTopologyTestSuite (4.96s)
    --- FAIL: TestRandomizedTopologyTestSuite/TestConnectedness_ClusterChannel (0.65s)
        helper.go:64: 
            	Error Trace:	helper.go:64
            	            				helper.go:145
            	            				randomizedTopology_test.go:175
            	Error:      	Not equal: 
            	            	expected: 34
            	            	actual  : 33
            	Test:       	TestRandomizedTopologyTestSuite/TestConnectedness_ClusterChannel
```
flakey tests

**Review by tarakby — APPROVED** [review]
Approving given that we had reviewed all PRs on the feature branch.

**Review by AlexHentschel — APPROVED** [review]
🎉

**Pull request merged**
