### PR TITLE
chore(localnet): faster account creation

### PR DESCRIPTION
**Pull request by SaveTheRbtz**

### CODE REVIEW

**Review by pattyshack — APPROVED** [review]

**Comment by simonhf** [comment]
@SaveTheRbtz tried this out -- and unfortunately had to grapple with multiple issues just to get flow-go building and running -- but finally it ran and this PR does not work for me [1] :-(

Here's an example block of logs from the loader with an error:

```
1657137430.955733 Wed Jul  6 19:57:10 2022 7:57PM INF creating accounts cumulative=0 num=750 numberOfAccounts=4800
1657137432.557620 Wed Jul  6 19:57:12 2022 7:57PM DBG new block parsed blockHeight=1 blockID=9ff6d6a2e2bc591f70c2c76e385a9f9ff31d14940ee792d21ecf6b12591ca944 numCollections=0 numSeals=0 timeSinceLastBlockInMS=1601.773171 timeToGetBlockByHeightInMS=0.862287 timeToParseBlockInMS=0.871431 txsInBlock=0 txsInBlockUnknown=0 txsInProgress=0 txsTotal=0 txsTotalUnknown=0
1657137433.457087 Wed Jul  6 19:57:13 2022 7:57PM DBG new block parsed blockHeight=2 blockID=129901be821f1ce24c0cc20811d1d9a90ff774c8ac2b5e2df1fe31c05b541bf1 numCollections=0 numSeals=0 timeSinceLastBlockInMS=899.40865 timeToGetBlockByHeightInMS=0.562467 timeToParseBlockInMS=0.571586 txsInBlock=0 txsInBlockUnknown=0 txsInProgress=0 txsTotal=0 txsTotalUnknown=0
1657137434.357240 Wed Jul  6 19:57:14 2022 7:57PM DBG new block parsed blockHeight=3 blockID=0c83261e9d4746fdb78e8b97816fc86539813448d83fa54dd5a9c092123f5485 numCollections=0 numSeals=0 timeSinceLastBlockInMS=900.0353 timeToGetBlockByHeightInMS=0.615593 timeToParseBlockInMS=0.624846 txsInBlock=0 txsInBlockUnknown=0 txsInProgress=0 txsTotal=0 txsTotalUnknown=0
1657137435.257165 Wed Jul  6 19:57:15 2022 7:57PM DBG new block parsed blockHeight=4 blockID=406296ced128b34068045de3a8281497045f926d70ff768886c680919f495f47 numCollections=0 numSeals=0 timeSinceLastBlockInMS=899.866887 timeToGetBlockByHeightInMS=0.655627 timeToParseBlockInMS=0.663403 txsInBlock=0 txsInBlockUnknown=0 txsInProgress=0 txsTotal=0 txsTotalUnknown=0
1657137436.161419 Wed Jul  6 19:57:16 2022 7:57PM DBG new block parsed blockHeight=5 blockID=62140eb9c6174b43cabce7da18430b0373c62d242db50c9fbdbc583b247197e0 numCollections=0 numSeals=0 timeSinceLastBlockInMS=904.132329 timeToGetBlockByHeightInMS=4.574243 timeToParseBlockInMS=4.584415 txsInBlock=0 txsInBlockUnknown=0 txsInProgress=0 txsTotal=0 txsTotalUnknown=0
1657137437.157029 Wed Jul  6 19:57:17 2022 7:57PM DBG new block parsed blockHeight=6 blockID=8411089d8da8e48846095f6542c2da008c4f17ecec3cda4a77e6eb1503a1fd3e numCollections=0 numSeals=0 timeSinceLastBlockInMS=995.526131 timeToGetBlockByHeightInMS=0.706252 timeToParseBlockInMS=0.716309 txsInBlock=0 txsInBlockUnknown=0 txsInProgress=0 txsTotal=0 txsTotalUnknown=0
1657137438.057243 Wed Jul  6 19:57:18 2022 7:57PM DBG new block parsed blockHeight=7 blockID=b397fc128eaaa41714e24ba5e3d7d523c6941f8dece9f19851cc4821027149bc numCollections=0 numSeals=0 timeSinceLastBlockInMS=900.062387 timeToGetBlockByHeightInMS=0.588793 timeToParseBlockInMS=0.597974 txsInBlock=0 txsInBlockUnknown=0 txsInProgress=0 txsTotal=0 txsTotalUnknown=0
1657137438.957129 Wed Jul  6 19:57:18 2022 7:57PM DBG new block parsed blockHeight=8 blockID=dd7ddbbac974a1363c7b291a2e59703d6abcff4eafc51028e49d4938d817f9a2 numCollections=0 numSeals=0 timeSinceLastBlockInMS=899.792775 timeToGetBlockByHeightInMS=0.692303 timeToParseBlockInMS=0.70288 txsInBlock=0 txsInBlockUnknown=0 txsInProgress=0 txsTotal=0 txsTotalUnknown=0
1657137440.457942 Wed Jul  6 19:57:20 2022 7:57PM DBG new block parsed blockHeight=9 blockID=b47e6e8ab474899214461b3c74b50146cb1c120c27e9dde38de53d3264b94a3c numCollections=1 numSeals=0 timeSinceLastBlockInMS=1500.714672 timeToGetBlockByHeightInMS=0.597925 timeToParseBlockInMS=1.174919 txsInBlock=1 txsInBlockUnknown=1 txsInProgress=0 txsTotal=1 txsTotalUnknown=1
1657137440.857577 Wed Jul  6 19:57:20 2022 7:57PM DBG new block parsed blockHeight=10 blockID=f89aa1911b093dc68b55efa54df9df18eaca04698bc39d1a2b5fe171e66ec53a numCollections=0 numSeals=0 timeSinceLastBlockInMS=399.583125 timeToGetBlockByHeightInMS=0.818534 timeToParseBlockInMS=0.827067 txsInBlock=0 txsInBlockUnknown=0 txsInProgress=0 txsTotal=1 txsTotalUnknown=1
1657137440.975714 Wed Jul  6 19:57:20 2022 7:57PM ERR account creation tx failed error="[Error Code: 1101] cadence runtime error Execution failed:\nerror: [Error Code: 1110] computation exceeds limit (9999)\n  --> 3d604f5513d6541f3f581cdb6e171a022a33ffded6822cc536d54d7d77117552:12:6\n   |\n12 |       let account = AuthAccount(payer: signer)\n   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n" tx_id=3d604f5513d6541f3f581cdb6e171a022a33ffded6822cc536d54d7d77117552
```

Any ideas how to fix it?

[1] https://www.notion.so/dapperlabs/Examining-localnet-mtrie-traversal-cost-bcabebfa88bb41ffa06ada7e19231b9b

**Comment by SaveTheRbtz** [comment]
I've rebased and re-pushed it.  The 999999 limit should've been on the `createAccounts` transaction

**Review by simonhf — APPROVED** [review]
With the latest fixes then this PR appears to work :-) Notes about testing here [1].

[1] https://www.notion.so/dapperlabs/Examining-localnet-mtrie-traversal-cost-bcabebfa88bb41ffa06ada7e19231b9b#88eeb0fa156b42468a4ca2a0a8d17a75

**Comment by SaveTheRbtz** [comment]
bors merge

**Pull request merged**
