### PR TITLE
Internalize state/meter creation

### PR DESCRIPTION
**Pull request by pattyshack**
Also renamed NewStateHolder to NewStateTransaction in preparation for renaming
the struct.

### CODE REVIEW

**Review by SaveTheRbtz — APPROVED** [review]

**Review by zhangchiqing — APPROVED** [review]
Nice refactor

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Pull request merged**
