### PR TITLE
Simplify SaveExecutionResults arguments

### PR DESCRIPTION
**Pull request by pattyshack**

### CODE REVIEW

**Review by SaveTheRbtz — APPROVED** [review]
`cmd/util/cmd/rollback-executed-height/cmd/rollback_executed_height_test.go` would need to be fixed too

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
urgh.  looks like the lint error is due to accidental cyclic import.  I'm going to mv utils/unittest/mocks.ExecutionState into engine_test.go (since it's the only test that uses it) to break up the cycle

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Pull request merged**
