### PR TITLE
[Consensus] Enable linting on consensus

### PR DESCRIPTION
**Pull request by zhangchiqing**
Just noticed the linting was disabled on consensus/hotstuff package. This PR fixes the linting errors after enabling it again

### CODE REVIEW

**Review by durkmurder — APPROVED** [review]
Nice catch, thanks

**Review by huitseeker — APPROVED** [review]
Yes!
(this would be a good candidate for a bors-merge)

**Comment by zhangchiqing** [comment]
bors-merge

**Comment by huitseeker** [comment]
bors merge

**Pull request merged**
