### PR TITLE
draft [Hotfix] to fix signer indices decoding

### PR DESCRIPTION
**Pull request by AlexHentschel**
implements hotfix for https://github.com/onflow/flow-go/issues/3115

### CODE REVIEW

**Comment by AlexHentschel** [comment]
confirmed with localnet that the changes are working (extended the wait-time to 3min using the `connect-timeout` flag):
```
grpcurl -connect-timeout 180 -plaintext -protoset ~/Development/onflow/access.pb localhost:3569 flow.access.AccessAPI/GetLatestBlockHeader | jq 
```

response
```json
{
  "block": {
    "id": "s7TYuCfvaojO2F8Aw/JAvXpB6AXpBRn1rfn9S/jAlro=",
    "parentId": "+XEntOt9fnTdb9HPbwAfJFbLivgBNaAt8o2HUvQ72qQ=",
    "height": "37",
    "timestamp": "2022-08-30T19:00:57.382680796Z",
    "payloadHash": "iW9uYWjl0SvBeXkWCckyT3gEu4IccAsRHXuZ4dle75s=",
    "view": "59",
    "parentVoterIds": [
      "XOwif1aoZ7MDtwsJXpqXvcDy5JbSgilgdCuRcPheEcU=",
      "5IpJXsZLSXywA+/SlMMDUIrzsFEjzOP3GsW9GYXfZGk=",
      "/SDyQ2et9kGa7Rfx3/ihxgxx9QYDiFwb7ybnzKtLs5Y="
    ],
    "parentVoterSigData": "+GQAsJS4F4RVSv6OMF8yLJytss/+BZ6H2L8y2HnP/bsTwzSnYbtauPiQXunMF+h20RDsqoCwiiwbBe62r1/sPtNCqpmUTvoL8KgxHmApn5p7uCr+TOnj7O5pjz9o2WZyQiwtV5dd",
    "proposerId": "5IpJXsZLSXywA+/SlMMDUIrzsFEjzOP3GsW9GYXfZGk=",
    "proposerSigData": "qT56h4I3/IKAfUPzZhbAxgHsLn2lKqtr/EnsOQU01el6A7hjxHIFb5zOd1HqVm/thIgx1o0o2DLDKYfU2NuddAyK5H5FiiYz/7r4o+pHLAIIwTzooDkUFovKkty7eeHx",
    "chainId": "flow-localnet",
    "parentVoterIndices": "OZICsOA="
  }
}
```
🎉

**Comment by AlexHentschel** [comment]
ported changes to mainnet 18: https://github.com/onflow/flow-go/pull/3126

**Review by zhangchiqing — APPROVED** [review]
Thanks for fixing it!

**Review by peterargue — APPROVED** [review]

**Comment by AlexHentschel** [comment]
bors merge

**Comment by AlexHentschel** [comment]
bors retry

**Pull request merged**
