### PR TITLE
Make ledger read safe to tampering

### PR DESCRIPTION
**Pull request by ramtinms**
For the safety reasons, it's better to make a copy of values stored on the ledger instead of returning the pointers.

### CODE REVIEW

**Comment by m4ksio** [comment]
I agree with general direction, Im not sure if that's the best to do so - ie. shall we maybe do it in other layer before passing to FVM? I just think potential performance penalty, maybe I overreact

**Comment by ramtinms** [comment]
@m4ksio wouldn't be the same performance impact even on the FVM layer?

**Comment by m4ksio** [comment]
> @m4ksio wouldn't be the same performance impact even on the FVM layer?

I was thinking we can avoid copying altogether in some cases, but we should go with better solution and if this ever becomes a bottleneck we can optimise.

**Review by Kay-Zee — APPROVED** [review]
Played around with the test, with and with out the changes.

Makes sense to me.

**Comment by ramtinms** [comment]
@m4ksio is this ready to go? I can't approve the PR since I've created it

**Review by m4ksio — APPROVED** [review]

**Comment by m4ksio** [comment]
> @m4ksio is this ready to go? I can't approve the PR since I've created it

I think so.

**Pull request merged**
