### PR TITLE
[Consensus] Replace `DecreasingPruningHeightError` with `BelowPrunedThresholdError`

### PR DESCRIPTION
**Pull request by durkmurder**
https://github.com/dapperlabs/flow-go/issues/6318

### CODE REVIEW

**Review by jordanschalm — APPROVED** [review]
🎸

**Review by AlexHentschel — APPROVED** [review]
🏄‍♂️

**Comment by durkmurder** [comment]
bors merge

**Comment by durkmurder** [comment]
bors merge

**Pull request merged**
