### PR TITLE
[CI][Testing] Fix Flaky Test Monitor in CI - replace `run-tests.sh` bash script with GitHub Actions

### PR DESCRIPTION
**Pull request by gomisha**
### Context

Flaky Test Monitor has been relying on a bash script (`tools/test_monitor/run-tests.sh`) to run all tests before uploading the results to BigQuery. This is problematic for many reasons:

- the bash script would often fail in CI without transparency of the failure; a failure is NOT a test failure but another kind of failure that prevents the job from completing
- the bash script was running all unit tests as a single process instead of splitting them up the way our regular CI process does (`.github/workflows/ci.yml`)
- the bash script was duplicating the work of the main CI workflow (`.github/workflows/ci.yml`) by splitting out the integration tests
- the bash script took a long time to run - it would take about 1.5 hours to complete a single flaky test run of all tests

The goal of this PR is to remove the reliance on this script and to use the same CI workflows to run unit and integration tests as the main CI process (`ci.yml`), including splitting up unit tests into packages and running each package as a separate CI job.

### Highlights
- replaces `/tools/test_monitor/run-tests.sh` with GitHub Actions 
- creates reusable workflow snippet (`.github/workflows/actions/test-monitor-process-results/action.yml`) that's used in multiple places in the main workflow (`.github/workflows/flaky-test-monitor.yml`) for processing test results and uploading them to BigQuery
- renames `.github/workflows/test-monitor-regular-skipped.yml` to `.github/workflows/flaky-test-monitor.yml` since there's no more need to have a flaky and a normal workflow (a single workflow covers both scenarios)
- deletes redundant workflows: `.github/workflows/test-monitor-flaky.yml`, `.github/workflows/flaky-test-debug.yml`
- CI runtime reduced by about 3-5x (20-30 minutes to run vs 1.5 hours with bash script)

### CODE REVIEW

**Review by peterargue — APPROVED** [review]

**Comment by peterargue** [comment]
Looks good. A couple general questions:

1. this will run more frequently and using more executors than before. How will that affect the regular PR/merge CI jobs?
2. can this be run manually from the PR before merging?

**Review by tarakby — APPROVED** [review]
Nice refactor. Looks good to me. 

> CI runtime reduced by about 3-5x (20-30 minutes to run vs 1.5 hours with bash script)

The time to test flakiness got reduced which is great, but does that impact the CI time run for every PR update? I mean does that CI job now run slower because of the extra flakiness work?

Another question: do we still need `.github/workflows/flaky-test-debug.yml` ?

**Comment by gomisha** [comment]
> The time to test flakiness got reduced which is great, but does that impact the CI time run for every PR update? I mean does that CI job now run slower because of the extra flakiness work?

It might but we can change the flaky tests to run less frequently than every 2 hours or have them run more frequently outside of regular work hours and on weekends. The current version of Flaky Test Monitor already runs every 2 hours with multiple runners for each type of integration test. We're going to have more runners required for unit tests now but we can monitor the situation and adjust if necessary.

>Another question: do we still need .github/workflows/flaky-test-debug.yml ?

Great suggestion. I removed it! https://github.com/onflow/flow-go/pull/4589/commits/8e62777d3226f36262b855fbd0171d47e2a44262

**Comment by gomisha** [comment]
Thanks for the questions @peterargue!

> 1. this will run more frequently and using more executors than before. How will that affect the regular PR/merge CI jobs?

The frequency is actually the same as the current Flaky Test Monitor which runs every 2 hours already and is using multiple GH runners. The only difference is the extra GH runners required for splitting out the unit test runs. We can monitor the situation and we can change the flaky tests workflow to run less frequently than every 2 hours or have it run more frequently outside of regular work hours and on weekends. We can monitor the situation and adjust if necessary.

> 2. can this be run manually from the PR before merging?

No it can't but that's the purpose of the regular CI workflow (`.github/workflows/ci.yml`) which runs the same tests (as the flaky tests workflow) on every PR push and merge.

**Pull request merged**
