### PR TITLE
move snapshot related code into a separate package

### PR DESCRIPTION
**Pull request by pattyshack**
separate out public snapshot interfaces away from internal implementation detail (fvm/storage/state).  (I'm planning combine the derived indices with the primary index in fvm/storage.  Moving snapshot tree into the snapshot package cleans up the circular dependency)

### CODE REVIEW

**Review by SaveTheRbtz — APPROVED** [review]

**Review by janezpodhostnik — APPROVED** [review]

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Pull request merged**
