### PR TITLE
Add an extra parameter for runtime config in `NewCustomReusableCadenceRuntimePool` constructor

### PR DESCRIPTION
**Pull request by m-Peter**
Prior to this change, an empty `runtime.Config{}` was used and there was no way to set a custom config.

A similar improvement was done in this PR https://github.com/onflow/flow-go/pull/3768

### CODE REVIEW

**Review by pattyshack — APPROVED** [review]

**Review by janezpodhostnik — APPROVED** [review]

**Comment by sideninja** [comment]
@m-Peter can you merge in master to update this PR?

**Comment by m-Peter** [comment]
@sideninja well, there's a handy button for when you are in mobile, and I used it 😂 gotta love technology 💞 merged in master branch 🙏

**Comment by janezpodhostnik** [comment]
I think benchstat is having issues with the fact that this is a PR with a fork. Let me look into that.

**Comment by janezpodhostnik** [comment]
https://github.com/onflow/flow-go/pull/4146

**Comment by m-Peter** [comment]
@janezpodhostnik Will do, thanks for resolving this :pray: :100:

**Comment by janezpodhostnik** [comment]
bors merge

**Pull request merged**
