### PR TITLE
[Don't merge yet][Flow EVM] Capture coinbase as part of transaction executed events

### PR DESCRIPTION
**Pull request by ramtinms**
This PR captures the coinbase context as part of the tx executed event. 

This update needs an HCU.

### CODE REVIEW

**Comment by sideninja** [comment]
Yes, this is better approach than mine for sure. Good idea. Can you finish it up?

**Review by sideninja — APPROVED** [review]

**Review by janezpodhostnik — APPROVED** [review]

**Comment by ramtinms** [comment]
Please do not merge!

**Comment by ramtinms** [comment]
We might consider #6380 instead of this PR

**Comment by ramtinms** [comment]
closing this one for now.

**Pull request closed without merging**
