### PR TITLE
adding secure-rpc-addr to access node systemd file

### PR DESCRIPTION
**Pull request by vishalchangrani**

### CODE REVIEW

**Review by huitseeker — APPROVED** [review]
Thanks!

**Review by smnzhu — APPROVED** [review]
👍

**Review by zhangchiqing — APPROVED** [review]

**Comment by huitseeker** [comment]
@vishalchangrani you could use bors for this one too

**Comment by vishalchangrani** [comment]
bors merge

**Comment by huitseeker** [comment]
bors retry

**Pull request merged**
