### PR TITLE
Jwinkler2083233/turbo crypto

### PR DESCRIPTION
**Pull request by jwinkler2083233**
This code integrates with the XKCP library, which was compiled separately.

### CODE REVIEW

**Comment by jwinkler2083233** [comment]
The CI 'checks' are flaky.  Sometimes the linter works.  Sometimes the Unit tests for 1.16 work, but not 1.15.  To get past the checks, I'm going to run these in an infinite loop until both checks pass in the same run.

**Comment by jwinkler2083233** [comment]
Here's the plan:
* separate the associated files from libXKCP
* include them via CGO
* use the precompiler settings from Tarak to trigger the correct code to compile at build time

**Comment by tarakby** [comment]
I suggest to close this PR. It got first replaced by another PR https://github.com/onflow/flow-go/pull/1354, which got closed itself because of performance regression.

**Comment by jwinkler2083233** [comment]
No appetite for this, so closing.

**Pull request closed without merging**
