### PR TITLE
Fix undefined: sha3State errors when building on arm64

### PR DESCRIPTION
**Pull request by peterargue**
After https://github.com/onflow/flow-go/pull/1865 was merged, we started seeing the following error while building flow on arm64 machines:
```
 => ERROR [build-production 2/3] RUN --mount=type=cache,target=/go/pkg/mod     --mount=type=cache,target=/root/.cache/go-build     GO111MODULE=on CGO_ENABLED=1 GOOS=linux go build --tags "relic,netg  0.6s
------
 > [build-production 2/3] RUN --mount=type=cache,target=/go/pkg/mod     --mount=type=cache,target=/root/.cache/go-build     GO111MODULE=on CGO_ENABLED=1 GOOS=linux go build --tags "relic,netgo" -ldflags "-extldflags -static     -X 'github.com/onflow/flow-go/cmd/build.commit=cedf6df37c81c5c82a199cd640aa0b503c5b96b7' -X  'github.com/onflow/flow-go/cmd/build.semver=v0.23.1-1557-gcedf6'"     -o ./app ./cmd/collection:
#21 0.593 # github.com/onflow/flow-go/crypto/hash
#21 0.593 crypto/hash/xor_generic.go:48:15: undefined: sha3State
#21 0.593 crypto/hash/xor_generic.go:59:27: undefined: sha3State
------
executor failed running [/bin/sh -c GO111MODULE=on CGO_ENABLED=1 GOOS=linux go build --tags "relic,netgo" -ldflags "-extldflags -static     -X 'github.com/onflow/flow-go/cmd/build.commit=${COMMIT}' -X  'github.com/onflow/flow-go/cmd/build.semver=${VERSION}'"     -o ./app ./cmd/${TARGET}]: exit code: 2
make: *** [docker-build-collection] Error 1
```

This appears to be because the `sha3State` struct was replaced by `spongeState`, but the refactor missed this one file.

### CODE REVIEW

**Review by AlexHentschel — APPROVED** [review]

**Review by tarakby — APPROVED** [review]
Thanks for the fix! 
My bad I missed this in my previous PR. It's unfortunate the CI doesn't include an ARM run yet. We started adding it some time ago and hopefully it'll be available soon!

**Comment by peterargue** [comment]
bors merge

**Comment by peterargue** [comment]
bors merge

**Comment by peterargue** [comment]
bors merge

**Pull request merged**
