### PR TITLE
feat(localnet): use grafana, tempo, loki

### PR DESCRIPTION
**Pull request by SaveTheRbtz**
This diff switches localnet to the production-grade monitoring stack:
* Grafana (metrics)
* Tempo (Tracing)
* Loki (Logs)

Here is an example of plotting the rate of slow transactions in the logs and going to the traces for the log line:
Screen Shot 2022-05-28 at 12 36 46 AM

Also pre-provisioned a dashboard based on "Bechnet1 - General":
Screen Shot 2022-06-01 at 9 13 04 PM
Screen Shot 2022-06-01 at 9 13 40 PM

While here, removed logstash, kibana, elasticsearch, and jaeger.

Plan:
- [x] see whether promtail can be easily used instead of a [docker log driver](https://grafana.com/docs/loki/latest/clients/docker-driver/).
  - [x] if not, make driver installation automatic.
- [x] pre-create a localnet benchmark dashboard.
- [x] lock docker images versions so they won't accidentally break under us on upgrade.
- [x] fix documentation.

### CODE REVIEW

**Comment by SaveTheRbtz** [comment]
@ramtinms as a main user of jaeger previously, when you have time, can you please check the new setup for the observability in localnet proposed in this PR.  What does it miss?

**Review by ramtinms — APPROVED** [review]
Nice work 👏 , this looks great

**Review by Kay-Zee — APPROVED** [review]
Looks good! Got it running!

I think it makes sense to update the query for the consensus node to "sum" by "num" for both queries.

also, the loader graphs don't work currently, but i think that's fine.

Not sure if there are any traces on the default dashboard, or if i'm just missing it, but yeah, otherwise, looks good!

Screen Shot 2022-06-06 at 4 09 15 PM

**Comment by SaveTheRbtz** [comment]
The `num` tag was broken for localnet, so I've fixed it.  While there also added a prometheus push gateway so that loader can emit metrics in localnet environment.

**Comment by SaveTheRbtz** [comment]
bors merge

**Comment by SaveTheRbtz** [comment]
bors merge

**Comment by SaveTheRbtz** [comment]
bors merge

**Comment by simonhf** [comment]
@SaveTheRbtz @gomisha unfortunately the change to the docker loki driver breaks the current localnet loader automation. Why? Before this change it tails the log files in real-time to monitor for errors and transaction execution failures. With the old docker logging then the log files were simply laying around on the host OS for easy access. With this change the files get piped into loki instead of regular files for each log file. Also, after each load test run and before this change, the docker log files for each node would be copied and compressed. This means after, say, 7 load tests then all logs from all nodes for each load test are preserved and greppable, etc.

I'm wonder if there is a way to keep loki and never-the-less have the old functionality?

Is there a way to tail loki logs efficiently in real-time?

Is there a way to efficiently copy and compress all loki logs after the load test is complete?

If these are not possible, then maybe it's possible to somehow create a man-in-the-middle driver which efficiently grabs the logs before passing them onto loki? In this way the logs could be monitored and archived as well as available in loki?

Thoughts? Does anybody have experience do something like this?

**Comment by simonhf** [comment]
After some Googling: Is using `loki` via `promtail` a solution? Why? This article [1] suggests that `promtail` "the source logs are read directly from /var/lib/docker/containers in the host filesystem, so you have to mount this volume in the Promtail container, where with the Docker Log driver, you don´t need to." In theory, this might allow loki and the automation scripts to co-exist?

[1] https://brunopaz.dev/blog/better-docker-log-search-experience-with-loki/

**Comment by SaveTheRbtz** [comment]
Will [setting](https://grafana.com/docs/loki/latest/clients/docker-driver/configuration/) `keep-file` solve your immediate problem?

Also, you can consider using Loki directly to pull the logs via its HTTP API:
* https://grafana.com/docs/loki/latest/api/#get-lokiapiv1tail 
* https://grafana.com/docs/loki/latest/api/#get-lokiapiv1query_range
(As a side bonus it does support [LogQL](https://grafana.com/docs/loki/latest/logql/) in the query.)

Ideally, I would like to avoid saving logs on disk and then tailing them back to loki for them to be saved on disk again.

**Comment by simonhf** [comment]
Thanks for the tips! I'll take look :-)

**Comment by simonhf** [comment]
Tested the PR loki fix via promtail here [1] with the load test automation scripts and it works :-)

Next problem is that the old docker Jaeger all-in-one container is no more and the automation scripts download the Jaeger traces from that container after the load test. Is the new / replacement container 'tempo'? Now need to figure out how to achieve the equivalent Jaeger span download from the new container...

[1] https://github.com/onflow/flow-go/pull/2609

**Comment by simonhf** [comment]
@SaveTheRbtz discovered that tempo port 3200 is not accessible from the host. I used the following hack to make it available:

```
$ git diff docker-compose.metrics.yml 
diff --git a/integration/localnet/docker-compose.metrics.yml b/integration/localnet/docker-compose.metrics.yml
index 682ffd9f1a..0432fe33eb 100644
--- a/integration/localnet/docker-compose.metrics.yml
+++ b/integration/localnet/docker-compose.metrics.yml
@@ -8,6 +8,7 @@ services:
       - ./data/tempo:/tmp/tempo:z
     ports:
       - "14268"
+      - "3200:3200"
```

It would be great to have it available to the host by default.

Still working on using the API to extract all the trace and span IDs.

**Comment by SaveTheRbtz** [comment]
@simonhf can you please submit a PR for this?

**Comment by simonhf** [comment]
I'm going to try to get the download from tempo working first. It remains to be seen if downloading all trace IDs and associated span IDs from tempo is efficient enough to be realistic. If tempo doesn't cut it then the PR probably will be a waste of time.

So far, I have managed to download a set of span IDs for a particular trace ID. But the data looks a bit funny... I'm wondering if I'm requesting it in the wrong way, or if tempo is getting confused with the jaeger data being sent to it. Will continue to investigate tomorrow :-)

**Comment by SaveTheRbtz** [comment]
If you are currently blocked by this, by all means please bring jaeger back into a separate docker-compose yaml, add a make file section for bringing it up if it needed and make a tracing endpoint configurable in bootstrap.

For the long term, it would still be better to switch to tempo spans, since:
* Jaeger HTTP JSON API endpoint is internal and will likely change/break over time.  (they explicitly describe it as "This JSON API is intentionally undocumented and subject to change.")
* In production we would have Tempo so it would be nice if the scripts would be able to analyze not only localnet traces, but also the production ones.

**Comment by simonhf** [comment]
So hacking / replacing tempo with jaeger again works, e.g.:

```
$ cat docker-compose.metrics.yml 
version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  loki:
    image: grafana/loki:main-9218e46
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    volumes:
      - ./data/loki:/loki:z
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:main-9218e46
    command: -config.file=/etc/promtail/promtail-config.yaml
    volumes:
      - ./conf/promtail-config.yaml:/etc/promtail/promtail-config.yaml:z
      - /var/run/docker.sock:/var/run/docker.sock:z

  prometheus:
    image: prom/prometheus:v2.36.0
    volumes:
      - ./conf/prometheus.yaml:/etc/prometheus/prometheus.yaml:z
      - ./targets.nodes.json:/etc/prometheus/targets.nodes.json:z
      - ./data/prometheus:/prometheus:z
    command: "--config.file=/etc/prometheus/prometheus.yaml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090

  pushgateway:
    image: prom/pushgateway:v1.4.3
    ports:
      - 9091:9091

  exporter:
    image: prom/node-exporter:v1.3.1
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana:9.0.0-beta3
    volumes:
      - ./conf/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:z
      - ./conf/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:z
      - ./conf/grafana-localnet.json:/etc/grafana/provisioning/dashboards/localnet.json:z
      - ./conf/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
```

But when localnet is up then this is what my `docker ps` looks like:

```
$ docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                                                                                  NAMES
2b8cbc04870b        localnet-consensus                "/bin/app --nodeid=4…"   16 seconds ago      Up 14 seconds       0.0.0.0:3709->9002/tcp                                                                                 localnet_consensus_2_1
ae6101b0cbf0        localnet-consensus                "/bin/app --nodeid=7…"   16 seconds ago      Up 14 seconds       0.0.0.0:3710->9002/tcp                                                                                 localnet_consensus_3_1
c8bb90a7ffea        localnet-collection               "/bin/app --nodeid=f…"   16 seconds ago      Up 14 seconds       0.0.0.0:3706->9002/tcp                                                                                 localnet_collection_5_1
45a89d7ab0bb        localnet-collection               "/bin/app --nodeid=5…"   16 seconds ago      Up 14 seconds       0.0.0.0:3705->9002/tcp                                                                                 localnet_collection_4_1
9b188a7f2c4b        localnet-collection               "/bin/app --nodeid=c…"   16 seconds ago      Up 14 seconds       0.0.0.0:3704->9002/tcp                                                                                 localnet_collection_3_1
e40b5a2bdba9        localnet-collection               "/bin/app --nodeid=a…"   16 seconds ago      Up 14 seconds       0.0.0.0:3703->9002/tcp                                                                                 localnet_collection_2_1
216f21d215d8        localnet-collection               "/bin/app --nodeid=c…"   16 seconds ago      Up 14 seconds       0.0.0.0:3707->9002/tcp                                                                                 localnet_collection_6_1
b1f3431b4fcc        localnet-consensus                "/bin/app --nodeid=9…"   17 seconds ago      Up 15 seconds       0.0.0.0:3708->9002/tcp                                                                                 localnet_consensus_1_1
e9fafedecb8f        localnet-access                   "/bin/app --nodeid=8…"   17 seconds ago      Up 15 seconds       0.0.0.0:1235->1234/tcp, 0.0.0.0:3571->9000/tcp, 0.0.0.0:3572->9001/tcp                                 localnet_access_2_1
0eac4372ece5        localnet-collection               "/bin/app --nodeid=3…"   17 seconds ago      Up 15 seconds       0.0.0.0:3702->9002/tcp                                                                                 localnet_collection_1_1
53f40e7f5d00        localnet-execution                "/bin/app --nodeid=8…"   17 seconds ago      Up 15 seconds       0.0.0.0:3602->9000/tcp, 0.0.0.0:3603->9001/tcp, 0.0.0.0:3701->9002/tcp                                 localnet_execution_2_1
d2a6abcbf88e        localnet-access                   "/bin/app --nodeid=6…"   18 seconds ago      Up 16 seconds       0.0.0.0:1234->1234/tcp, 0.0.0.0:3569->9000/tcp, 0.0.0.0:3570->9001/tcp                                 localnet_access_1_1
bceaeb9a5861        localnet-execution                "/bin/app --nodeid=f…"   18 seconds ago      Up 16 seconds       0.0.0.0:3600->9000/tcp, 0.0.0.0:3601->9001/tcp, 0.0.0.0:3700->9002/tcp                                 localnet_execution_1_1
af89a9d2943c        localnet-verification             "/bin/app --nodeid=6…"   18 seconds ago      Up 16 seconds       0.0.0.0:3711->9002/tcp                                                                                 localnet_verification_1_1
90ca3418ff2c        grafana/promtail:main-9218e46     "/usr/bin/promtail -…"   28 seconds ago      Up 26 seconds                                                                                                              localnet_promtail_1
919d3733f9a8        prom/pushgateway:v1.4.3           "/bin/pushgateway"       28 seconds ago      Up 26 seconds       0.0.0.0:9091->9091/tcp                                                                                 localnet_pushgateway_1
92557283ef54        grafana/grafana:9.0.0-beta3       "/run.sh"                28 seconds ago      Up 26 seconds       0.0.0.0:3000->3000/tcp                                                                                 localnet_grafana_1
b13be5d6a034        jaegertracing/all-in-one:latest   "/go/bin/all-in-one-…"   28 seconds ago      Up 26 seconds       5775/udp, 5778/tcp, 14250/tcp, 6832/udp, 14268/tcp, 0.0.0.0:6831->6831/udp, 0.0.0.0:16686->16686/tcp   localnet_jaeger_1
40816e5c0e15        prom/node-exporter:v1.3.1         "/bin/node_exporter"     28 seconds ago      Up 27 seconds       0.0.0.0:9100->9100/tcp                                                                                 localnet_exporter_1
```

I have never used loki before, but I would expect there to be a loki container? Should there be?

And when I ask who is listening on port 3100 -- i.e. the loki port? -- then I also find no listeners:

```
$ netstat -an | egrep LISTEN | egrep 3100
$
```

So I'm wondering if this PR is working correctly? Or am I misunderstanding something about how loki works?

**Pull request merged**
