### PR TITLE
[ledger] further optimize sha3 for amd64

### PR DESCRIPTION
**Pull request by tarakby**
Addresses https://github.com/dapperlabs/flow-go/issues/5481

- Use a specific assembly implementation of Keccak rounds (main operation of sha3) for amd64 (copied from the Go standard lib)
- Use unaligned versions of copy in and out of the sha3 state for amd64
- keep the non-amd64 versions

This gives a 10% time improvement for the ledger customized sha3:

Before:
```
BenchmarkHash/LedgerSha3-8               2616789               458 ns/op
BenchmarkHash/GenericSha3-8              1300896               926 ns/op
```

After:
```
BenchmarkHash/LedgerSha3-8               2947566               405 ns/op
BenchmarkHash/GenericSha3-8              1299237               926 ns/op
```

### CODE REVIEW

**Review by ramtinms — APPROVED** [review]
It looks good to me, if the genesis and other constant state commitment haven't changed in the code I assume it works great.

**Comment by ramtinms** [comment]
Might worth adding some methods to compare the outcome of our hash function against the standard go one with several random inputs.

**Comment by tarakby** [comment]
>Might worth adding some methods to compare the outcome of our hash function against the standard go one with several random inputs.
Right, that test exists [here](https://github.com/onflow/flow-go/blob/master/ledger/common/hash/hash_test.go#L24-L55).

**Review by AlexHentschel — APPROVED** [review]
👍

**Pull request merged**
