### PR TITLE
cruisectl delay implementation bias (fix for deployment branch `v0.37`)

### PR DESCRIPTION
**Pull request by AlexHentschel**
this PR contains a temporary solution for the implementation bias observed for Cruise Control on Testnet. 
* The issue was first reported here: https://flow-foundation.slack.com/archives/C071612SJJE/p1723722918506329

This code targets the crescendo deployment branch `v0.37`. This affects only testnet (and not in a critical manner). Fix if fully downwards compatible. Hence, this can be rolled out as part of any future release to testnet and mainnet. 

## Intuition behind the changes: 

- The call to [`forks.AddValidatedBlock` emits the `OnBlockIncorporated` notification](https://github.com/onflow/flow-go/blob/d9f7522d6c502d7e148dab69c926279202677cf8/consensus/hotstuff/forks/forks.go#L261) for `block` with view $v$, which the `BlockTimeController` uses as [its starting point for the view](https://github.com/onflow/flow-go/blob/d9f7522d6c502d7e148dab69c926279202677cf8/consensus/hotstuff/cruisectl/block_time_controller.go#L476-L481).   
- While the [`MessageHub` delays block publication](https://github.com/onflow/flow-go/blob/d9f7522d6c502d7e148dab69c926279202677cf8/engine/consensus/message_hub/message_hub.go#L433-L437), this delay is only observed by nodes other than the primary.
* For the primary itself, the [`EventHandler` adds its own proposal right away](https://github.com/onflow/flow-go/blob/d9f7522d6c502d7e148dab69c926279202677cf8/consensus/hotstuff/eventhandler/event_handler.go#L390-L417) to `Forks`: https://github.com/onflow/flow-go/blob/d9f7522d6c502d7e148dab69c926279202677cf8/consensus/hotstuff/eventhandler/event_handler.go#L390-L417
  Hence, the proposer itself observes the `OnBlockIncorporated` for its own block much earlier. 
* So in the case, where node `A` is the **primary for two _consecutive_ views**:
   - the delay for the later proposal is computed relative to the _construction time_ of the parent
   - however, the delay for the later proposal should be computed relative to the _publication time_ of the parent
   - As the _construction time_ of the parent is about 450ms before the _publication time_, the controller's limits of authority restrict the largest possible delay. Statistically this bias affects 1/n of the views, with `n` the number of consensus nodes. On testnet, the bias is expected to be a lot more severe (n=7) compared to mainnet (n=100).

--- 

For an extended version of this fix for `master`, please see  [PR  #6379](https://github.com/onflow/flow-go/pull/6379)

### CODE REVIEW

**Review by jordanschalm — APPROVED** [review]
Looks good - I agree it would be better for block signing to also pass through safety rules, though. Reasoning through the safety would be much easier that way.

**Comment by jordanschalm** [comment]
I tagged `v0.37.4-pr6379` to test on Testnet.

**Comment by AlexHentschel** [comment]
this should be included into our `deployment branch` for testnet. 
version for `master` 👉  https://github.com/onflow/flow-go/pull/6392

**Comment by AlexHentschel** [comment]
**running on Testnet** and successfully removing Cruise Control Bias 👉 [slack](https://flow-foundation.slack.com/archives/CUU2KQL4A/p1724168298988919)

**Review by j1010001 — APPROVED** [review]

**Pull request merged**
