### PR TITLE
Refactor manager banchmark test

### PR DESCRIPTION
**Pull request by pattyshack**
Prep work for benchmarking concurrent execution

### CODE REVIEW

**Review by janezpodhostnik — APPROVED** [review]

**Review by zhangchiqing — APPROVED** [review]

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors retry

**Comment by pattyshack** [comment]
bors retry

**Comment by pattyshack** [comment]
bors retry

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors retry

**Comment by pattyshack** [comment]
bors retry

**Comment by pattyshack** [comment]
bors retry

**Comment by pattyshack** [comment]
bors retry

**Pull request merged**
