### PR TITLE
v0.29.16 height coordinated upgrade

### PR DESCRIPTION
**Pull request by peterargue**
Merge changes for height-coordinated upgrade into main release branch

### CODE REVIEW

**Review by pattyshack — APPROVED** [review]
rubberstamp

**Review by janezpodhostnik — COMMENTED** [review]
looks ok to me, but why are we merging this back into v0.29?

I'm not sure I follow...

Previously we had a new minor version for each spork, but more importantly we had a minor version for each protocol breaking change (for each change where we couldn't do a rolling upgrade if you will). But now that is sort of breaking down as a node running on 0.29 and a node running on 0.29.16 cannot run on the same network...

**Comment by peterargue** [comment]
@janezpodhostnik that's a good point. We haven't been creating new branches for height-coordinated upgrades, and we've had 2-3 already on v0.29. Merging back is most consistent with the way we've handled this in the last couple of versions, but I think this deserves some more consideration going forward.

**Review by turbolent — APPROVED** [review]
Reviewed the Cadence-related commits

**Pull request merged**
