### PR TITLE
Fix sync engine bug, improve observability

### PR DESCRIPTION
**Pull request by jordanschalm**
* Fixes a bug in the sync engine, where many sync `Status` objects would share a reference to the same `Header` due to a re-used loop variable (see https://github.com/onflow/flow-go/commit/a874156937a518704c14edbb8a0a4a4832dee3b1)
* Adds the chain ID to the sync core, making it possibly to easily differentiate between follower and cluster sync core logs, on collection nodes
* Adds the chain ID to the chainsync metrics, for the same reason

### CODE REVIEW

**Review by durkmurder — APPROVED** [review]
Looks good

**Review by AlexHentschel — APPROVED** [review]
great catch 👏

**Comment by jordanschalm** [comment]
bors merge

**Comment by jordanschalm** [comment]
bors merge

**Pull request merged**
