### PR TITLE
[Security] Remove unknown codeowners

### PR DESCRIPTION
**Pull request by sideninja**
Removing non-existing code owners from reviewers. This is a potential security vulnerability since you can create an account with those usernames and start approving changes.

### CODE REVIEW

**Review by tarakby — APPROVED** [review]
Good catch! Thank you 🙏🏼

**Review by zhangchiqing — APPROVED** [review]

**Comment by tarakby** [comment]
bors merge

**Comment by sideninja** [comment]
should I merge manually or what is the process with bors?

**Comment by tarakby** [comment]
> should I merge manually or what is the process with bors?

You can merge manually, but `bors merge` will spare you time waiting for tests to pass. I guess you are happy with the changes so I can go ahead and merge the PR

**Comment by tarakby** [comment]
bors merge

**Pull request merged**
