### PR TITLE
Modify Localnet image-build behaviour, update documentation

### PR DESCRIPTION
**Pull request by jordanschalm**
The original default behaviour for Localnet was to always re-build all images, every time a new network was started. At some point, this default behaviour changed, so that images are not re-built, but the documentation was not updated.

This diff:
- changes default behaviour back to build images each time localnet is started (original behaviour: trade-speed-for-safety)
- adds option (make start-cached etc) to start without building images (current behaviour: trade-safety-for-speed)
- updates the documentation

### CODE REVIEW

**Review by durkmurder — APPROVED** [review]
Also had issues with it, definitely a much needed fix.

**Comment by bluesign** [comment]
Would be also really nice to publish images for versions, if I want to run mainnet12 (as localnet) it should be easy to pull images for that.

**Review by zhangchiqing — APPROVED** [review]

**Comment by jordanschalm** [comment]
> Would be also really nice to publish images for versions, if I want to run mainnet12 (as localnet) it should be easy to pull images for that.

These images are built and should be available publicly (at `gcr.io/flow-container-registry/$ROLE`) with tag corresponding to the version (eg `v0.29.x` for Mainnet22).

We would need to change the image name expected by Localnet to use those images, eg. here:
https://github.com/onflow/flow-go/blob/6aa808eb240bc19860b9c93f40689a5ae7bd5a08/integration/localnet/bootstrap.go#L501

**Comment by jordanschalm** [comment]
bors merge

**Comment by jordanschalm** [comment]
bors retry

**Pull request merged**
