### PR TITLE
[Access Node] implement proxy connection factory

### PR DESCRIPTION
**Pull request by smnzhu**
This PR implements the proxy connection factory that can be used on unstaked access nodes.

closes https://github.com/dapperlabs/flow-go/issues/5698

### CODE REVIEW

**Review by huitseeker — COMMENTED** [review]
Considering both tests are nearly identical, would it make sense to extract a private function for them that each would call with slightly different parameters?

**Comment by smnzhu** [comment]
> Considering both tests are nearly identical, would it make sense to extract a private function for them that each would call with slightly different parameters?

Ah this is a great point. After looking into it more though, I'm not sure it would be possible to refactor it much more than this,  due to the fact the `GetExecutionAPIClient` and `GetAccessAPIClient` have different names, and handlers `ExecutionAPIServer`, `AccessAPIServer` and clients `ExecutionAPIClient`, `AccessAPIClient` all have different types. Even the `PingRequest` have different types for the two APIs. As far as I know, due to generics not yet being supported in Golang, I don't see a good way to refactor this :(

**Review by huitseeker — APPROVED** [review]
Thanks!

**Comment by huitseeker** [comment]
> Ah this is a great point. After looking into it more though, I'm not sure it would be possible to refactor it much more than this, due to the fact the `GetExecutionAPIClient` and `GetAccessAPIClient` have different names, and handlers `ExecutionAPIServer`, `AccessAPIServer` and clients `ExecutionAPIClient`, `AccessAPIClient` all have different types. Even the `PingRequest` have different types for the two APIs. As far as I know, due to generics not yet being supported in Golang, I don't see a good way to refactor this :(

Yeah, it's probably an area where you want to to use closures and empty-ish interfaces (🙀 ). Which, given that requires error management, is too much work for the context of this PR.

**Review by vishalchangrani — APPROVED** [review]
🍻 lgtm

**Pull request merged**
