### PR TITLE
Combine TransactionState & DerivedTransactionData into a single interface

### PR DESCRIPTION
**Pull request by pattyshack**
TransactionState and DerivedTransactionData should eventually be validated and committed together using 2PC.

The two are now folded into the storage.Transaction, which hides the implementation detail and enables us to swap in a concurrency managed implementation in the future.

This also moved away from using NewSimpleView in tests wherever possible.

### CODE REVIEW

**Review by janezpodhostnik — APPROVED** [review]
This was a big one!

**Review by zhangchiqing — APPROVED** [review]

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Pull request merged**
