### PR TITLE
Make meter a required argument to NewState.  Also remove NoOp/Basic meter

### PR DESCRIPTION
**Pull request by pattyshack**
weighted meter becomes the only available option

### CODE REVIEW

**Review by SaveTheRbtz — APPROVED** [review]

**Comment by SaveTheRbtz** [comment]
Speaking about deleting code, I think I should look at removing stdout tracer.

**Review by janezpodhostnik — APPROVED** [review]
Changes look good.

Since the weighted meter is now the only meter, it doesn't make sense to have it in its own folder I think.

**Comment by pattyshack** [comment]
yeah, i need to do a bunch of other meter related refactoring.  I'll get the code organized in future PRs.

**Comment by pattyshack** [comment]
hmm. actually,  i'll just do it in this diff while i'm at it

**Comment by pattyshack** [comment]
errrr ... nevermind.  that requires quite a bit of changes.  i'll do it in a different pr

**Comment by pattyshack** [comment]
bors merge

**Pull request merged**
