### PR TITLE
Use tagged versions of core contract repos

### PR DESCRIPTION
**Pull request by joshuahannan**
Updates go.mod to use the new tagged versions of the core contract repos.

The new versions were tested using the latest cadence, flow-go-sdk, emulator, and CLI versions

### CODE REVIEW

**Comment by turbolent** [comment]
👍 

Looks like the tagged version is for another commit. Can you please add a one-liner to the description how that tagged commit differs from the previous one we used?

**Comment by joshuahannan** [comment]
Yes, I updated the description. I just updated the dependencies in all the repos

**Review by turbolent — APPROVED** [review]
v1.0.0! 👏 🎉

**Comment by turbolent** [comment]
cc @bjartek

**Comment by bjartek** [comment]
Amazing!

**Review by peterargue — APPROVED** [review]

**Pull request merged**
