### PR TITLE
Update to Cadence v0.36.0

### PR DESCRIPTION
**Pull request by dsainati1**
## Description

Update to:
- [onflow/flow-go-sdk v0.35.0](https://github.com/onflow/flow-go-sdk/releases/tag/v0.35.0)
- [onflow/cadence v0.36.0](https://github.com/onflow/cadence/releases/tag/v0.36.0)

Port from v0.29:
- #3910
- #3920
- #3969
- #3997

### CODE REVIEW

**Review by SupunS — APPROVED** [review]

**Comment by janezpodhostnik** [comment]
Is there any other change besides the mock and go.mod updates? It's hard to sift through all the files.

If there are other changes, would you mind extracting the mockery update into a separate PR?

**Comment by turbolent** [comment]
@janezpodhostnik You can select all commits but the last one to get a diff of the non-mockery changes

**Comment by turbolent** [comment]
I'll open a separate PR for the mockery update

**Comment by pattyshack** [comment]
+1 to janez's comment.  could you re-request review after the mockery updates out split out?  thx

**Review by pattyshack — COMMENTED** [review]
.

**Comment by turbolent** [comment]
@janezpodhostnik @pattyshack opened #4025

**Review by janezpodhostnik — APPROVED** [review]

**Review by pattyshack — APPROVED** [review]

**Comment by turbolent** [comment]
bors merge

**Pull request merged**
