### PR TITLE
log triedir when fail to initialize disk war

### PR DESCRIPTION
**Pull request by zhangchiqing**
Useful for debugging wrong config of the `triedir` flag

### CODE REVIEW

**Review by janezpodhostnik — APPROVED** [review]

**Review by fxamacker — APPROVED** [review]

**Comment by zhangchiqing** [comment]
bors merge

**Comment by zhangchiqing** [comment]
bors retry

**Comment by zhangchiqing** [comment]
bors retry

**Comment by zhangchiqing** [comment]
bors merge

**Comment by zhangchiqing** [comment]
bors retry

**Pull request merged**
