### PR TITLE
[Access] Upgrade lru cache v2

### PR DESCRIPTION
**Pull request by nozim**
Revised version of older PR (https://github.com/onflow/flow-go/pull/4605) synced from latest master.

### CODE REVIEW

**Comment by nozim** [comment]
@peterargue @jordanschalm @durkmurder kindly help to rerun the ci. 🙏

**Review by kc1116 — APPROVED** [review]

**Comment by nozim** [comment]
@kc1116 kindly help to rerun the ci. Updated from latest master.

**Review by peterargue — APPROVED** [review]

**Comment by nozim** [comment]
@peterargue @kc1116 thanks for approval. Will have to wait for updates in master to ensure the tests pass. I will ask you to merge afterwards 🙏

**Comment by peterargue** [comment]
@nozim looks like `TestExecutionEvictingCacheClients` is the test that failed, and is also affected by these changes. Have you looked into why it's failing?

**Pull request merged**
