### PR TITLE
Concurrent transaction execution skeleton

### PR DESCRIPTION
**Pull request by pattyshack**
I'll expose the concurrent execution option in a follow up PR.

Issue: #3547

### CODE REVIEW

**Review by pattyshack — COMMENTED** [review]
@zhangchiqing fyi, all your comments are from the original PR are addressed

**Review by janezpodhostnik — APPROVED** [review]
lgtm. In the future adding some metrics on the number of attempts per transaction would be great.

**Comment by pattyshack** [comment]
i'll add some metrics as a follow up.

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors retry

**Comment by pattyshack** [comment]
bors retry

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors retry

**Comment by pattyshack** [comment]
bors retry

**Comment by pattyshack** [comment]
bors retry

**Comment by pattyshack** [comment]
bors retry

**Comment by pattyshack** [comment]
bors retry

**Pull request merged**
