### PR TITLE
[Consensus] Revert unsealed reason

### PR DESCRIPTION
**Pull request by zhangchiqing**

### CODE REVIEW

**Review by durkmurder — APPROVED** [review]

**Review by AlexHentschel — APPROVED** [review]
🎉

**Comment by zhangchiqing** [comment]
bors merge

**Comment by zhangchiqing** [comment]
bors merge

**Comment by zhangchiqing** [comment]
bors merge

**Comment by zhangchiqing** [comment]
bors merge

**Comment by zhangchiqing** [comment]
bors merge

**Pull request merged**
