### PR TITLE
move blocks.go into environment subpackage

### PR DESCRIPTION
**Pull request by pattyshack**
also renamed some variables for better searchability.

### CODE REVIEW

**Review by Tonix517 — APPROVED** [review]
LGTM - assuming the lint errors will be fixed

**Comment by pattyshack** [comment]
oops.  i missed one file.  will fix

**Review by SaveTheRbtz — APPROVED** [review]

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors retry

**Review by zhangchiqing — APPROVED** [review]

**Comment by pattyshack** [comment]
bors merge

**Comment by SaveTheRbtz** [comment]
bors merge

**Comment by SaveTheRbtz** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors retry

**Pull request merged**
