### PR TITLE
[All] Go 1.19

### PR DESCRIPTION
**Pull request by SaveTheRbtz**
Aside from the [new features in 1.19](https://tip.golang.org/doc/go1.19) it will also give us 3-5% performance boost.
(FVM benchmark does not capture this because it is using the same go version on both checkouts.)

Interesting features for us are:
* `GOMEMLIMIT` so that we can run GC more rare than once in two minutes.
* New runtime metrics including: `/cgo/go-to-c-calls:calls` and `/gc/*`.
* Race detector is 2-3x faster.  Also `-asan` is available on Linux.

Depends on: #3136 #3137 #3140 #3141 #2988

### CODE REVIEW

**Comment by SaveTheRbtz** [comment]
bors try

**Comment by SaveTheRbtz** [comment]
bors try

**Review by pattyshack — APPROVED** [review]

**Review by gomisha — APPROVED** [review]

**Comment by SaveTheRbtz** [comment]
bors merge

**Comment by SaveTheRbtz** [comment]
bors merge

**Pull request merged**
