### PR TITLE
add Is<blah>Error to errors/

### PR DESCRIPTION
**Pull request by pattyshack**

### CODE REVIEW

**Comment by Tonix517** [comment]
could generics help here?

**Comment by pattyshack** [comment]
I don't think generics helps here:
1. we need different function names
2. the bodies will be replace by `HasErrorCode(err, <error code>)` in the next few days

**Review by zhangchiqing — APPROVED** [review]
Nice!

**Review by Tonix517 — APPROVED** [review]

**Comment by pattyshack** [comment]
bors merge

**Pull request merged**
