### PR TITLE
Go 1.20

### PR DESCRIPTION
**Pull request by SaveTheRbtz**
Depends on: #3701

### CODE REVIEW

**Comment by tarakby** [comment]
There is a change about `math/rand` that deprecates `Seed` and `Read` in `1.20` and those are used heavily in our tests (and in some production code too). 
I still prefer to use  deterministic `math/rand` in many cases instead of `crypto/rand` because it helps reproducing bugs in tests. 

I suggest to update the `math/rand` usage in our tests before merging this PR (happy to help with that).

**Comment by Kay-Zee** [comment]
@tarakby does `crypto/rand` not provide the ability to use a deterministic rand? If so then we'd just have replace it properly in each case, no? I think we can make the change in this PR, probably.

**Comment by tarakby** [comment]
No `crypto/rand` is a true randomness that can't be seeded.
Yes we would need to update each use of `math/rand`. I will allocate some time for this work, it's also a good opportunity to address a related ticket: https://github.com/dapperlabs/flow-internal/issues/1809.

**Comment by tarakby** [comment]
```
Error: ../../../../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.31.1/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
```

These errors on CI complain about the package `lucas-clemente/quic-go` that can't build for 1.20. It is used by `go-libp2p` for which there isn't a 1.20 release yet. 

```
go mod why -m github.com/lucas-clemente/quic-go
# github.com/lucas-clemente/quic-go
github.com/onflow/flow-go/network/p2p/p2pbuilder
github.com/libp2p/go-libp2p/config
github.com/lucas-clemente/quic-go
```
I guess this will block updating flow-go to 1.20.

**Comment by SaveTheRbtz** [comment]
[v0.26.3](https://github.com/libp2p/go-libp2p/releases/tag/v0.26.3) should have newer quick version with support for 1.19/1.20

**Pull request closed without merging**
