### PR TITLE
Read staged contracts from CSV file

### PR DESCRIPTION
**Pull request by SupunS**
Closes https://github.com/onflow/cadence/issues/3050

### CODE REVIEW

**Review by turbolent — APPROVED** [review]
Nice!

**Review by janezpodhostnik — COMMENTED** [review]
How are new line characters handled in the contract code? It looks like there shouldn't be any.

**Comment by turbolent** [comment]
@janezpodhostnik I'm fairly sure Go's CSV reader supports newlines (escaped; similar to e.g. also commas and quotes), but we can add a test case if needed

**Comment by SupunS** [comment]
multiline codes can be within quotes: https://github.com/onflow/flow-go/pull/5425/commits/890a62ea11bca5371469a010830a5328bcea117e. AFAIK, all writers automatically quote, if string content is multi-lined.

**Review by janezpodhostnik — APPROVED** [review]

**Comment by SupunS** [comment]
The failing test `TestGossipSubIHaveBrokenPromises_Above_Threshold` seems intermittent, and passes locally. It is also not related to the changes here, so will go head and going to merge the PR.

**Pull request merged**
