### PR TITLE
Pass zerolog by value

### PR DESCRIPTION
**Pull request by janezpodhostnik**
There was no reason for passing zerolog around by reference

### CODE REVIEW

**Review by zhangchiqing — APPROVED** [review]

**Comment by Kay-Zee** [comment]
What was the reason to make this change? Is it just that by ref was not necessary or is there some other tangible benefit?

**Comment by janezpodhostnik** [comment]
@Kay-Zee just cleanup as I noticed it doing other stuff, and I did not want to include it in a PR that also does other things.

**Review by sideninja — APPROVED** [review]

**Comment by fxamacker** [comment]
Want to share some thoughts but I don't have a strong preference.

I think the refactor to pass by value looks cleaner but maybe passing logger by ref can be less fragile.

If a newer version of a logger adds an internal lock, then passing logger by value can end up copying the new lock.

As one way to use logger, Cloudflare just returns `*zerolog.Logger` when [creating logger](https://github.com/cloudflare/cloudflared/blob/b474778cf1bf9b26a1de67372c090771c786516e/logger/create.go#L102) in cloudflare/cloudflared:

```Go
func newZerolog(loggerConfig *Config) *zerolog.Logger
```

**Comment by janezpodhostnik** [comment]
@fxamacker that is a good argument. IMO whatever we choose, we should be consistent.

Currently we mostly pass zerolog by value. So it might be better to just do that consistently. I just took a look and there is only 3 other locations that use it by reference. I will check if I can change those too.

I feel like that if in the future we actually need to pass zerolog by reference we can just change all instances to references then.

**Comment by fxamacker** [comment]
Sounds good!

> that is a good argument

Pun intended?  :laughing:

**Pull request merged**
