### PR TITLE
Test ErrorsCollector against SplitError

### PR DESCRIPTION
**Pull request by pattyshack**
Forgot to add test for this during the refactoring.

### CODE REVIEW

**Review by Tonix517 — APPROVED** [review]
LGTM - please remove `.failures.go.swp` before merging.

**Comment by pattyshack** [comment]
thx for point that out.  i'll fix my gitignore while i'm at it.

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors retry

**Comment by pattyshack** [comment]
bors retry

**Review by janezpodhostnik — APPROVED** [review]

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors retry

**Comment by pattyshack** [comment]
bors merge

**Pull request merged**
