### PR TITLE
update default values for epoch, staking and DKG length

### PR DESCRIPTION
**Pull request by kc1116**
epoch length - 10000
staking length - 2000
DKG length - 2000

### CODE REVIEW

**Comment by simonhf** [comment]
Just linking this issue to this sibling issue here: https://github.com/dapperlabs/flow-go/issues/5709

**Review by huitseeker — COMMENTED** [review]
I've seen @jordanschalm mention non-zero defaults [here](https://github.com/dapperlabs/flow-go/issues/5709#issuecomment-889949226).
I notice the default setup here:
https://github.com/onflow/flow-go/blob/f2547a26b1c53153daba8ad03d0bdddfa117ca89/cmd/bootstrap/cmd/finalize.go#L91-L93
which seems to be used in the absence of other instructions (other instructions you're setting here for localnet).
I haven't found a setting of 200 / 5/ 80.

QQ: 
- do we want to change the general default or the one for localnet? 
- Do we want these numbers, sp. for the staking phase length (usually 1/10 the DKG length)? 
- Is there a 3d palce where @jordanschalm 's numbers are set?

**Comment by kc1116** [comment]
> I've seen @jordanschalm mention non-zero defaults [here](https://github.com/dapperlabs/flow-go/issues/5709#issuecomment-889949226).
> I notice the default setup here:
> https://github.com/onflow/flow-go/blob/f2547a26b1c53153daba8ad03d0bdddfa117ca89/cmd/bootstrap/cmd/finalize.go#L91-L93
> 
> 
> which seems to be used in the absence of other instructions (other instructions you're setting here for localnet).
> I haven't found a setting of 200 / 5/ 80.
> QQ:
> 
> * do we want to change the general default or the one for localnet?
> * Do we want these numbers, sp. for the staking phase length (usually 1/10 the DKG length)?
> * Is there a 3d palce where @jordanschalm 's numbers are set?

**Review by huitseeker — COMMENTED** [review]
LGTM!

**Review by jordanschalm — APPROVED** [review]

**Review by huitseeker — APPROVED** [review]

**Pull request merged**
