### PR TITLE
Sync Pacemaker Branch to `v0.29`

### PR DESCRIPTION
**Pull request by jordanschalm**
https://github.com/onflow/flow-go/pull/3764
https://github.com/onflow/flow-go/pull/3763

### CODE REVIEW

**Review by AlexHentschel — APPROVED** [review]
🚢

**Review by durkmurder — APPROVED** [review]

**Comment by durkmurder** [comment]
bors merge

**Comment by jordanschalm** [comment]
bors retry

**Comment by jordanschalm** [comment]
bors retry

**Pull request merged**
