### PR TITLE
[v0.31] Update to Cadence v0.39.8

### PR DESCRIPTION
**Pull request by turbolent**
Port of #4468 to `v0.31`

### CODE REVIEW

**Comment by fxamacker** [comment]
@turbolent We also need to update flow-emulator to use latest Cadence.

https://github.com/onflow/flow-emulator/pull/419

**Comment by turbolent** [comment]
bors merge

**Review by fxamacker — APPROVED** [review]

**Comment by turbolent** [comment]
bors retry

**Comment by turbolent** [comment]
bors retry

**Comment by turbolent** [comment]
bors retry

**Pull request merged**
