### PR TITLE
[Networking] Explicitly set resource limits in tests

### PR DESCRIPTION
**Pull request by SaveTheRbtz**
By default libp2p [autoscales limits based on available system memory](https://github.com/libp2p/go-libp2p/blob/2f0d7502981e8e0806e5a47da493220becc23659/p2p/host/resource-manager/limit_defaults.go#L307-L312).  This is irrelevant in production but in tests flakes rate is inversely proportional to the amount of memory a container has. (This also makes it hard to reproduce the flake locally.)

While here also bump `github.com/libp2p/go-libp2p-resource-manager` to v0.5.3 and reset `streamCount` to 100 in `TestCreateStream.*` tests to verify the fix.

This diff should also fix some of the p2p-related "Unit test" flakes.

### CODE REVIEW

**Review by pattyshack — APPROVED** [review]

**Comment by SaveTheRbtz** [comment]
bors try

**Comment by SaveTheRbtz** [comment]
bors try

**Comment by SaveTheRbtz** [comment]
bors try

**Comment by SaveTheRbtz** [comment]
bors try

**Review by gomisha — APPROVED** [review]

**Review by kc1116 — APPROVED** [review]

**Comment by SaveTheRbtz** [comment]
bors merge p=200

**Pull request merged**
