### PR TITLE
Update to Go 1.22

### PR DESCRIPTION
**Pull request by turbolent**
Go 1.20 has been unsupported since Go 1.22 got released, three months ago.

Update to Go 1.22 to get latest improvements.

See https://discord.com/channels/613813861610684416/1235013191633993749

### CODE REVIEW

**Comment by turbolent** [comment]
@peterargue Looks like some of the mocks in some tests (`TestHandler`) need to be adjusted (`mock.AnythingOfType("*context.emptyCtx")` should probably be just `mock.Anything`?)

**Comment by peterargue** [comment]
> @peterargue Looks like some of the mocks in some tests (`TestHandler`) need to be adjusted (`mock.AnythingOfType("*context.emptyCtx")` should probably be just `mock.Anything`?)

yea, I think the's the right way to fix

**Review by sideninja — APPROVED** [review]

**Review by janezpodhostnik — APPROVED** [review]
🚀

**Comment by tarakby** [comment]
Do we also want to update the linter version from 1.54 to 1.59? https://github.com/onflow/flow-go/pull/6037/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL52

**Comment by turbolent** [comment]
@tarakby yeah, please feel free to open a PR

**Comment by tarakby** [comment]
I meant to include it here since it's related, but yes we can update it in another PR

**Pull request merged**
