### PR TITLE
[Ledger] Fix a typo in copy function

### PR DESCRIPTION
**Pull request by sideninja**
Fix a typo in the for loop definition.

### CODE REVIEW

**Review by janezpodhostnik — APPROVED** [review]
How come this did not get cough by CI?

**Review by tarakby — APPROVED** [review]
Thank you!

**Comment by tarakby** [comment]
> How come this did not get cough by CI?
@janezpodhostnik There are 2 implementations, one for amd64 CPUs and one generic. The typo is in the generic files, while the CI machine must have been using an amd64.

**Comment by sideninja** [comment]
@tarakby feel free to merge this whenever you think it's appropriate

**Comment by tarakby** [comment]
I will follow up on this to make sure the CI runs also on a non-amd64 architecture.

**Pull request merged**
