### PR TITLE
Fix tests to use correct increasing tx index

### PR DESCRIPTION
**Pull request by pattyshack**
The upcoming changes to program cache will use txIndex as logical time for
optimistic concurrency control.

Fixing the tests up front / in a separate PR since the program cache changes
are massive enough by themselves.

### CODE REVIEW

**Review by SaveTheRbtz — APPROVED** [review]

**Review by Tonix517 — APPROVED** [review]
LGTM

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
crap ... i messed up rebasing ...

**Pull request merged**
