### PR TITLE
chore(tests): regen mocks

### PR DESCRIPTION
**Pull request by SaveTheRbtz**
Ran `make generate-mocks`.

cc: @gomisha @AndrewM-SDET  should we add this to a pre-commit action to check for an empty diff?  I would assume, mocks should always be re-generated.

### CODE REVIEW

**Review by pattyshack — APPROVED** [review]

**Comment by Tonix517** [comment]
I'd vote for the idea of removing all generated mock files from repo and only regenerate them when needed in Makefiles.

**Comment by SaveTheRbtz** [comment]
@Tonix517  In ideal world when we have a proper build system (e.g. bazel) we could generate mocks, protobufs, etc using genrules on demand w/o committing them to the repo.  For now though,... babysteps.

**Review by AndrewM-SDET — APPROVED** [review]

**Comment by SaveTheRbtz** [comment]
bors merge

**Comment by SaveTheRbtz** [comment]
bors cancel

**Comment by SaveTheRbtz** [comment]
closed by: #2799

**Pull request closed without merging**
