### PR TITLE
Detect and log unrecognized domains during migration

### LINKED ISSUE #6076: Migrations should detect and log unrecognized domains
Currently, migrations are silently mishandling unrecognized domains.

We should update migrations to at least detect and log unrecognized domains.

For context, some unrecognized domains were found today while manually examining binary payloads data:
- https://github.com/onflow/flow-go/issues/6069
- https://github.com/onflow/flow-go/issues/6072

### PR DESCRIPTION
**Pull request by fxamacker**
Closes #6076 

Currently, migrations are silently mishandling payloads from unrecognized domains.

This PR updates atree migration to detect and log unrecognized domains.

For context, some unrecognized domains were found today while manually examining binary payloads data:
- https://github.com/onflow/flow-go/issues/6069
- https://github.com/onflow/flow-go/issues/6072

### CODE REVIEW

**Review by turbolent — APPROVED** [review]
Good idea!

**Comment by fxamacker** [comment]
@janezpodhostnik PTAL :pray:

**Review by janezpodhostnik — APPROVED** [review]
Nice, did we find some unexpected domains already?

**Comment by fxamacker** [comment]
> Nice, did we find some unexpected domains already?

@janezpodhostnik Yes, `path_cap` and `acc_cap` on testnet.

**Pull request merged**
