### PR TITLE
remove redundant address validity checks in AccountKeyReader

### PR DESCRIPTION
**Pull request by dreamsmasher**
A follow-up to #3444 which was merged by bors before i could push these changes.

As @janezpodhostnik mentioned in [this thread](https://github.com/onflow/flow-go/pull/3444#discussion_r1005881790), the existence of an address is already done in `statefulAccounts.getPublicKeyCount` and `statefulAccounts.getPublicKey`, making the check redundant from `AccountKeyReader`.

The only implementation for the `Accounts` interface currently is `StatefulAccounts`, as well as generated mocks and `FakeAccounts` in the unit tests. This adds a new assumption that these methods on `Accounts` will always verify an address's existence first, which may change in the future.

### CODE REVIEW

**Review by pattyshack — APPROVED** [review]
thx for the cleanup

**Review by janezpodhostnik — APPROVED** [review]
Thank you very much!

**Comment by dreamsmasher** [comment]
bors merge

**Comment by dreamsmasher** [comment]
good bot

**Pull request merged**
