### PR TITLE
Auto update to onflow/flow-go-sdk v0.41.11

### PR DESCRIPTION
**Pull request by SupunS**
## Description

Automatically update to:
- [onflow/flow-go-sdk v0.41.11](https://github.com/onflow/flow-go-sdk/releases/tag/v0.41.11)

### CODE REVIEW

**Review by turbolent — APPROVED** [review]

**Comment by janezpodhostnik** [comment]
Lokks like cadence is already at v0.42.0

only flow-go-sdk is being updated here

**Comment by turbolent** [comment]
@janezpodhostnik Yes, a previous PR updated Cadence, this one just bumps the SDK. The update tool just always uses the title/link in description

**Comment by SupunS** [comment]
Yeah, this one only updates the flow-go-sdk, so the transitive dependencies to Cadence are also updated to `v0.42.0`

**Review by fxamacker — APPROVED** [review]

**Review by sideninja — APPROVED** [review]

**Comment by SupunS** [comment]
bors merge

**Comment by SupunS** [comment]
bors retry

**Comment by SupunS** [comment]
bors retry

**Comment by turbolent** [comment]
Oh man, I think the merge queue is now failing to merge the PR, because it sees the failed bors ...

**Comment by turbolent** [comment]
Now that #4867 is open, we can maybe also just close this one

**Pull request closed without merging**
