### PR TITLE
Avoid setup/teardown cycle for skipped epoch integration tests; re-enable base Epoch Transition test

### PR DESCRIPTION
**Pull request by jordanschalm**
* Re-enable the base epoch transition test for the standard CI suite. It was marked as flakey in https://github.com/dapperlabs/flow-internal/issues/1613, however there is no CI log of a test-case-specific failure. There are many CI logs of [non-test-case-specific CI failures](https://github.com/dapperlabs/flow-go/issues/6042) seemingly related to a failure to initiate consensus (or observe it). There is no specific fix in this PR, however a general cause of integration test flakiness related to observing messages with the ghost node was recently addressed: https://github.com/onflow/flow-go/pull/1880. 
* Mark other epochs as flakey rather than resource-intensive for the time being (to get some data from flakey test monitor for their reliability on CI)
* move the `SkipUnless` statement to the suite instantiation - this avoids unnecessarily starting the network for skipped tests
* use a shorter staking auction length for the static epoch test, since there are no staking actions needed - saves some time for this test
* add/update a few comments

### CODE REVIEW

**Review by kc1116 — APPROVED** [review]

**Comment by jordanschalm** [comment]
Will revisit once https://github.com/onflow/flow-go/pull/1948 is merged

**Comment by jordanschalm** [comment]
updated - ready for review

**Review by kc1116 — APPROVED** [review]
:rocket:

**Review by zhangchiqing — APPROVED** [review]

**Comment by jordanschalm** [comment]
bors merge

**Pull request merged**
