### PR TITLE
Non relic build fix

### PR DESCRIPTION
**Pull request by janezpodhostnik**
Building without the `relic` flag should succeed, otherwise flow-go cannot be used in the emulator (which uses the non `relic` build).

blocks: https://github.com/onflow/flow-emulator/pull/66

### CODE REVIEW

**Review by huitseeker — COMMENTED** [review]
This looks great! Don't we want to add a non-relic build-only step to CI?

**Comment by janezpodhostnik** [comment]
@huitseeker It would be super helpful. I created a task for that: https://github.com/dapperlabs/flow-internal/issues/1544. This PR is meant to quickly fix the issue so that the emulator can be updated.

**Review by m4ksio — APPROVED** [review]

**Review by huitseeker — APPROVED** [review]
I'm erring on the side of accepting to unblock, @janezpodhostnik but :
- @tarak told me he would have a look
- It's unclear what scope of "buildability" you're aiming for since I can still see errors in the compilation of the whole project without the relic tag, see https://gist.github.com/ea134d3fb271826e79cb5df6b657e827
- thanks for the issue on adding a non-relic build in CI!

**Comment by tarakby** [comment]
Hi @janezpodhostnik,
The PR looks good but I have a question about the reasons of making the changes: I am wondering how the emulator uses directly or indirectly (through a package) the functions `RemoveBLSPublicKeys`, `NeutralBLSPublicKey`, or `AggregateBLSPublicKeys`. Is it to allow the emulator to verify QCs ?

**Comment by janezpodhostnik** [comment]
@tarakby @huitseeker 

My goal was to update flow-go in the emulator and I made a very naive approach of just trying to build it and fixing the build errors as I saw them. After that I ran the tests and examples in the flow-go-sdk to verify everything is still ok. I also checked that none of the panic I added was being hit.

I am not sure how exactly golang builds dependencies, but I suspect not all of flow-go needs to bu buildable for the emulator to be buildable. I went and checked which parts of flow-go the emulator depends on and it is these parts:

```
github.com/onflow/flow-go/access
github.com/onflow/flow-go/access/legacy
github.com/onflow/flow-go/engine/execution/state/delta
github.com/onflow/flow-go/fvm
github.com/onflow/flow-go/fvm/errors
github.com/onflow/flow-go/fvm/programs
github.com/onflow/flow-go/fvm/state
github.com/onflow/flow-go/fvm/utils
github.com/onflow/flow-go/model/flow
github.com/onflow/flow-go/storage

github.com/onflow/flow-go/crypto
github.com/onflow/flow-go/crypto/hash
```

I suspect `github.com/onflow/flow-go/crypto` is the one actually causing problems this time as it contains `RemoveBLSPublicKeys`, `NeutralBLSPublicKey`, and `AggregateBLSPublicKeys`

The only function actually used from `github.com/onflow/flow-go/crypto` is 2 x `crypto.DecodePublicKey`. I will check if removing these usages and thus not depending on `github.com/onflow/flow-go/crypto` also addresses the problem.

**Comment by janezpodhostnik** [comment]
I did some digging, here is what I found:

The first build error I encounter (without this PR) is:

```
# github.com/onflow/flow-go/module/signature
../../../go/pkg/mod/github.com/onflow/flow-go@v0.20.2/module/signature/signer_store.go:43:11: undefined: NewThresholdProvider
```

So I dug into why the emulator needs this in the first place. And it looks like the FVM needs it:

```
 > go mod why github.com/onflow/flow-go/module/signature
# github.com/onflow/flow-go/module/signature
github.com/onflow/flow-emulator
github.com/onflow/flow-go/fvm
github.com/onflow/flow-go/module/epochs
github.com/onflow/flow-go/consensus/hotstuff/verification
github.com/onflow/flow-go/module/signature
```

Fixing that, the second build error is:

```
# github.com/onflow/flow-go/consensus/hotstuff/verification
../flow-go/consensus/hotstuff/verification/common.go:83:23: undefined: "github.com/onflow/flow-go/crypto".NeutralBLSPublicKey
```

Which is actually coming from the same source:
```
> go mod why github.com/onflow/flow-go/consensus/hotstuff/verification
# github.com/onflow/flow-go/consensus/hotstuff/verification
github.com/onflow/flow-emulator
github.com/onflow/flow-go/fvm
github.com/onflow/flow-go/module/epochs
github.com/onflow/flow-go/consensus/hotstuff/verification
```

**Comment by tarakby** [comment]
Thanks for the detailed answer @janezpodhostnik!
I am looking at the FVM dependency to `github.com/onflow/flow-go/module/epochs` which might not be needed and I'm doing some experiments to see if we can go around it.
If that dependency is not needed, the emulator can build without further changes. I'll give an update on this soon.

**Comment by janezpodhostnik** [comment]
@tarakby thank you very much!

**Comment by tarakby** [comment]
@janezpodhostnik I've made some experiments but the dependencies are too many and cleaning them up is gonna take more efforts. A different solution involving cleaning up the crypto dependencies should come soon. For now we can unblock this PR and have the non-relic files.

**Pull request merged**
