### PR TITLE
[Benchmark] Non-blocking SetTPS

### PR DESCRIPTION
**Pull request by SaveTheRbtz**
Currently, `SetTPS` is a blocking call.  Since it only blocks in cases where we decrease TPS (waiting for current transaction to finish) -- it causes tests to be biassed towards lower numbers.

### CODE REVIEW

**Review by pattyshack — COMMENTED** [review]
just delete the wg?  there's no call where you set blocking to true ....

**Comment by SaveTheRbtz** [comment]
> just delete the wg? there's no call where you set blocking to true ....

fair enough!  let's make this code simpler!

**Review by gomisha — APPROVED** [review]

**Review by pattyshack — APPROVED** [review]

**Comment by SaveTheRbtz** [comment]
bors merge

**Comment by SaveTheRbtz** [comment]
bors merge

**Pull request merged**
