### PR TITLE
expose StartSpanFromRoot AccountFreezeEnabled methods to environment interface

### PR DESCRIPTION
**Pull request by pattyshack**

### CODE REVIEW

**Review by Tonix517 — APPROVED** [review]
LGTM. There are quite some flags in `Context`. Will all of them eventually be moved to `Environment`?

**Review by SaveTheRbtz — APPROVED** [review]

**Review by janezpodhostnik — APPROVED** [review]

**Comment by pattyshack** [comment]
most of the flags should be removed completely.  the optionality is just deadweight

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Pull request merged**
