### PR TITLE
Upgrade Cadence

### PR DESCRIPTION
**Pull request by janezpodhostnik**
to https://github.com/onflow/cadence/commit/ba9bfc7b2551b1e76b67af40c9d0e62e6746200a

### CODE REVIEW

**Review by pattyshack — APPROVED** [review]

**Comment by turbolent** [comment]
Keeping Cadence updates is great, so thank you for that! 

Is there a reason why it's a commit? Could we maybe just wait until a a proper new release is out? We were planning to tag one soon anyways

**Comment by pattyshack** [comment]
janez has are some pending changes on fvm side which requires the runtime interface update.  let's not block on an official release label

**Comment by turbolent** [comment]
@pattyshack @janezpodhostnik Sounds good! 👍

**Review by turbolent — APPROVED** [review]

**Comment by janezpodhostnik** [comment]
bors merge

**Pull request merged**
