### PR TITLE
Make ComputeBlock idempotent

### PR DESCRIPTION
**Pull request by pattyshack**
Use storage snapshot instead of view as input to remove unintentional side-effect modification.  Eventually, we want to selectively merge non-confliciting views within the computer.

### CODE REVIEW

**Review by zhangchiqing — APPROVED** [review]

**Review by janezpodhostnik — APPROVED** [review]

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors merge

**Comment by pattyshack** [comment]
bors retry

**Pull request merged**
