### PR TITLE
[Crypto] update Go dependencies

### PR DESCRIPTION
**Pull request by tarakby**
Update Go dependencies, in particular:
 - update `github.com/btcsuite/btcd/btcec/v2` to latest
 - `golang.org/x/crypto` to [June 2022](https://pkg.go.dev/golang.org/x/crypto@v0.0.0-20220622213112-05595931fe9d) (avoiding August 2022 version for now which deprecates `Curve` interface generic behaviour)

### CODE REVIEW

**Review by SaveTheRbtz — APPROVED** [review]

**Review by zhangchiqing — APPROVED** [review]

**Comment by tarakby** [comment]
bors merge

**Comment by SaveTheRbtz** [comment]
bors merge

**Comment by SaveTheRbtz** [comment]
With #3099 landed, unit tests should be less flakey on CI hosts, lets try it again:
bors merge

**Comment by SaveTheRbtz** [comment]
ok, the last try, after which i'll mark these tests as flakes.

bors merge

**Pull request merged**
