### PR TITLE
Update to Cadence v0.31.5-account-link-pragma

### PR DESCRIPTION
**Pull request by turbolent**
Cadence v0.31.5-account-link-pragma is v0.31.5 + account linking pragma (https://github.com/onflow/cadence/pull/2359 / onflow/cadence#2355)

### CODE REVIEW

**Review by SupunS — APPROVED** [review]

**Review by SupunS — COMMENTED** [review]
Maybe add an FVM test to ensure the pragma + flag works as intended

**Review by peterargue — APPROVED** [review]
Looks good. can you add a note to the description about what this adds/enables?

**Comment by turbolent** [comment]
@peterargue Linked the original PR (which was linked in the port PR), i.e. see the description in onflow/cadence#2355

**Comment by turbolent** [comment]
bors merge

**Comment by turbolent** [comment]
@j1010001 @SupunS @dsainati1 I enabled account linking for all chains, while requiring the use of the new pragma in [4f2e55e](https://github.com/onflow/flow-go/pull/3969/commits/4f2e55e8e1f51d6efed7aab4068453a498841bb3), please have a look

**Review by janezpodhostnik — APPROVED** [review]

**Review by SupunS — APPROVED** [review]
👌

**Review by pattyshack — APPROVED** [review]

**Comment by turbolent** [comment]
bors merge

**Pull request merged**
