### PR TITLE
Merge v0.25 to master

### PR DESCRIPTION
**Pull request by turbolent**
Now that the Mainnet spork is complete, merge the changes from `v0.25` back to `master`.

### CODE REVIEW

**Comment by janezpodhostnik** [comment]
I will close this one then: https://github.com/onflow/flow-go/pull/2264

**Review by janezpodhostnik — APPROVED** [review]
lgtm

**Comment by turbolent** [comment]
Ah, I didn't see this one. Yeah, might be good, as we'd also have to port the Cadence update

**Comment by turbolent** [comment]
bors merge

**Review by smnzhu — APPROVED** [review]

**Comment by janezpodhostnik** [comment]
bors merge

**Pull request merged**
