### PR TITLE
upgrade btcd dependency

### PR DESCRIPTION
**Pull request by vikstrous2**
There was a breaking change in btcd and this PR upgrades that dependency so users of flow-go can also upgrade their dependency on btcd.

To make things work, I also had to add replace directives so that the current version of the crypto sub-module is used. I also had to upgrade github.com/libp2p/go-libp2p-core to v0.16.1

### CODE REVIEW

**Review by tarakby — COMMENTED** [review]
Thanks for update! 
I suggested a different way to make the update below.

**Comment by tarakby** [comment]
Hi @vikstrous2, we're planning to make a similar package upgrade to the repo. I wanted to check if you're planning to make changes to the PR sometime soon or if I should go ahead and update it. Thanks

**Comment by vikstrous2** [comment]
Sorry, I totally forgot about this PR. I made these to like 10 repos before I ran out of steam. Feel free to just merge it in 2 parts yourselves if you have the bandwidth. I'll come back to this again later when all our dependencies are done upgrading.

**Comment by tarakby** [comment]
Closing the current PR, dependencies update is done by https://github.com/onflow/flow-go/pull/3085 and another PR to follow up soon.

**Pull request closed without merging**
