### PR TITLE
RLP modification to improve heap usage

### PR DESCRIPTION
**Pull request by jwinkler2083233**
This has a change to 'encode.go' from Ethereum/go-ethereum/rlp, so it's copying the 6-7 RLP files into the 'model/flow/rlp' directory.  If this change is accepted and integrated by Ethereum, the idea is to remove this directory and revert the changes at that time.

The change uses a sync.Pool to avoid a memory leak in the 'list()' method.

### CODE REVIEW

**Comment by jordanschalm** [comment]
Could you link to the `go-ethereum` PR so we can see the diff of the RLP changes?

**Review by fxamacker — CHANGES_REQUESTED** [review]
Hi Jeff,

> This has a change to 'encode.go' from Ethereum/go-ethereum/rlp, so it's copying the 6-7 RLP files into the 'model/flow/rlp' directory. If this change is accepted and integrated by Ethereum, the idea is to remove this directory and revert the changes at that time.
>
>The change uses a sync.Pool to avoid a memory leak in the 'list()' method.

It's great that you found an improvement that might be accepted by Ethereum!

Copying ~2500 lines from a 3rd-party project into flow-go with the idea of removing them later in a separate PR can create issues or confusion involving code reviews, legal, GitHub  metrics, and more.

It would be easier and safer to fork Ethereum's rlp package into a new repo and just change ~5 lines in flow-go to use the updated version.

Looking forward to seeing your improvements accepted into Ethereum's RLP codec.

**Comment by jwinkler2083233** [comment]
> Hi Jeff,
> 
> > This has a change to 'encode.go' from Ethereum/go-ethereum/rlp, so it's copying the 6-7 RLP files into the 'model/flow/rlp' directory. If this change is accepted and integrated by Ethereum, the idea is to remove this directory and revert the changes at that time.
> > The change uses a sync.Pool to avoid a memory leak in the 'list()' method.
> 
> It's great that you found an improvement that might be accepted by Ethereum!
> 
> Copying ~2500 lines from a 3rd-party project into flow-go with the idea of removing them later in a separate PR can create issues or confusion involving code reviews, legal, GitHub metrics, and more.
> 
> It would be easier and safer to fork Ethereum's rlp package into a new repo and just change ~5 lines in flow-go to use the updated version.
> 
> Looking forward to seeing your improvements accepted into Ethereum's RLP codec.

Hi Faye,

I didn't get a response from Ethereum.  I didn't really expect to.

Can you recommend the process for doing the fork?  What name to use, etc. ?  I tried modifying the RLP repo locally, and it didn't work for me so I went with this method.

**Comment by jwinkler2083233** [comment]
> Could you link to the `go-ethereum` PR so we can see the diff of the RLP changes?

??
This was my starting point (see below).  encode.go was the only file changed.
https://github.com/ethereum/go-ethereum/tree/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/rlp

**Comment by jordanschalm** [comment]
Hey @jwinkler2083233,

When you mentioned the plan was to have this change incorporated into `go-ethereum`, I assumed you had made a PR on their repo, hence that request for a link. I think it would still be a good idea to do this, since having the change accepted there means we don't need to maintain a fork. 

Regarding the process for forking, here is an example of a repo we have forked for use in `flow-go`: https://github.com/dapperlabs/testingdock.
* using the same repo name
* forked to the `dapperlabs` org

Since `go-ethereum` is a much bigger project with more frequent updates than other forks we use currently, I'd suggest we run the plan to begin depending on a fork by the team first in #flow-protocol.

**Comment by jwinkler2083233** [comment]
Here's the latest before and after comparison.

Before:
```
(pprof) Showing nodes accounting for 96635006, 82.81% of 116700167 total
Dropped 989 nodes (cum <= 583500)
Showing top 100 nodes out of 226
flat  flat%   sum%        cum   cum%
28836259 24.71% 24.71%   28836259 24.71%  [github.com/ethereum/go-ethereum/rlp.(*encbuf](http://github.com/ethereum/go-ethereum/rlp.(*encbuf)).list (inline)
4239344  3.63% 63.58%    4239344  3.63%  [github.com/ethereum/go-ethereum/rlp.(*encbuf](http://github.com/ethereum/go-ethereum/rlp.(*encbuf)).toBytes
```

After:
```
(pprof) Showing nodes accounting for 1713208044, 82.77% of 2069818576 total
Dropped 1757 nodes (cum <= 10349092)
Showing top 100 nodes out of 183
      flat  flat%   sum%        cum   cum%
 128612311  6.21% 58.03%  132281690  6.39%  github.com/onflow/flow-go/model/flow/rlp.EncodeToBytes
 ```

**Comment by fxamacker** [comment]
@jwinkler2083233 it looks like you're in good hands with @jordanschalm regarding the fork process.

And the team at ethereum-go appear to be interested and receptive to issue 24397 you opened.  👍

**Comment by Kay-Zee** [comment]
https://github.com/ethereum/go-ethereum/issues/24397 has been closed, with some suggestion using the latest master. We could explore using the manual encoder buffer management and re-evaluate

**Pull request closed without merging**
