### PR TITLE
Update to Cadence v1.0.0-M9

### PR DESCRIPTION
**Pull request by turbolent**
## Description

Automatically update to:
- [onflow/flow-go-sdk v1.0.0-M8](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-M8)
- [onflow/cadence v1.0.0-M9](https://github.com/onflow/cadence/releases/tag/v1.0.0-M9)

Note: Hide whitespace changes to see actual API adjustments

### CODE REVIEW

**Review by SupunS — APPROVED** [review]

**Comment by turbolent** [comment]
So weird, `TestGetAccountKey/Multiple_keys` fails, the order of the fields in the string representation of `AccountKey` changed? 🤔

**Comment by turbolent** [comment]
@SupunS I did a git bisect on the Cadence side, and it seems like the test starts to fail starting with https://github.com/onflow/cadence/commit/07a7f9742ef8e1115929ed5f6237f4bf18c9b151. No idea yet why those change would somehow influence the iteration _order_ of atree ordered map keys

**Comment by turbolent** [comment]
Given that `PublicKey` values are just normal composite values, I guess there is no guaranteed order, as the iteration order of atree ordered maps depends on e.g. the seed of the value. I adjusted the test

**Comment by turbolent** [comment]
Some tests fail, but they also fail on the target (feature) branch, due to #5482. Will merge anyway, we can fix those unrelated tests separately

**Pull request merged**
